-- WHO TURNED UP, AND WHAT THEY LOOKED AT.
--
-- ── WHAT THIS TURNS ON ───────────────────────────────────────────────────────
--
-- The dashboard could already say what the website PRODUCED: design tool
-- sessions, quote requests, enquiries. Every one of those is a row that already
-- exists. What it could not say was whether anybody turned up at all, how long
-- they stayed, which pages they read or where they came from. Nothing recorded
-- it. The tag in app/layout.js is a Google ADS conversion tag, not analytics,
-- and it keeps no visit history.
--
-- These two tables are the whole of it.
--
-- ── WHY TWO ROLL UP TABLES AND NOT ONE ───────────────────────────────────────
--
-- A visit that reads four pages is one visit and four page views. Rolled up per
-- page you can never add the pages together to get visits, because that same
-- visit is sitting on four rows. So the day's own figures get their own table
-- and the per page figures get another. The dashboard reads whichever answers
-- the question, and never adds one to get the other.
--
-- ── WHAT IS DELIBERATELY NOT STORED ──────────────────────────────────────────
--
-- No IP address, no user agent string, no name, no email, nothing a person
-- could be picked out by. A visitor is a hash of their address and browser
-- mixed with a salt that changes every day, so the same person on Tuesday and
-- Wednesday is two different hashes and nothing in the app can join them up.
-- That is what keeps this out of cookie banner territory: nothing is stored on
-- the visitor's machine except a session id that dies when the tab closes.
--
-- If proper returning visitor numbers are wanted later, that needs a stored
-- identifier and a consent notice, and it is a decision to be made out loud
-- rather than by adding a column.
--
-- ── THE RAW TABLE DOES NOT GROW FOR EVER ─────────────────────────────────────
--
-- Raw rows are pruned after ninety days by the nightly job. The roll ups are
-- kept for good: they are two small rows a day and they are what the dashboard
-- actually reads, so history stays intact while the big table stays small.
--
-- ── ONE DO BLOCK ─────────────────────────────────────────────────────────────
--
-- The Supabase SQL editor pools connections, and a script that errors part way
-- through has already committed whatever ran before it. One block means an
-- error anywhere undoes the lot.

do $$
begin

  -- ── one row per page view ─────────────────────────────────────────────────
  create table if not exists public.pcd_site_events (
    id bigserial primary key,

    -- Generated by the browser for THIS page view, and the reason a dwell time
    -- arriving thirty seconds later knows which row to land on. Unique, so a
    -- double send (React mounting twice in development, a beacon retried by the
    -- browser) inserts once rather than counting the same view twice.
    view_id text not null,

    -- One tab's browsing. Lives in sessionStorage, so it dies when the tab
    -- closes and never survives to another day.
    session_id text not null,

    -- Address and browser, salted with a salt that changes daily. See the note
    -- above: this cannot be turned back into a person and cannot be joined
    -- across days.
    visitor_hash text not null,

    -- Already stripped of its query string and trimmed, so /finishes?tab=edges
    -- and /finishes are one page rather than two.
    path text not null,

    -- Kept whole for the rare "who is linking to us" question. It is the site
    -- that linked, never anything about the person.
    referrer text,

    -- Worked out once, on the way in, in lib/pcd-site-tracking.js:
    -- ads, google, search, social, referral or direct.
    channel text not null default 'direct',

    utm_source text,
    utm_medium text,
    utm_campaign text,

    -- On the link Google Ads puts people through. This is what lets a visit be
    -- lined up against what the ads account actually billed.
    gclid text,

    device text not null default 'unknown',

    -- From Vercel's own geo headers. City and state, never finer.
    region text,

    -- Decided on the way in and never deleted. A third or more of raw hits are
    -- crawlers, and a figure that quietly includes them is worse than no figure
    -- at all. They are kept rather than dropped so "how much of this is bots"
    -- stays answerable.
    is_bot boolean not null default false,

    -- How long the page was actually VISIBLE, not how long the tab was open.
    -- Null until the beacon arrives, and null for ever if somebody closes the
    -- laptop lid.
    dwell_ms integer,

    created_at timestamptz not null default timezone('utc', now())
  );

  create unique index if not exists pcd_site_events_view_id
    on public.pcd_site_events (view_id);

  -- The roll up reads a day at a time, and the prune deletes by age.
  create index if not exists pcd_site_events_created_idx
    on public.pcd_site_events (created_at);

  -- Sessions are grouped constantly: visits, bounce rate, pages per visit, and
  -- which channel a session arrived on.
  create index if not exists pcd_site_events_session_idx
    on public.pcd_site_events (session_id, created_at);

  -- ── the day's own figures ─────────────────────────────────────────────────
  create table if not exists public.pcd_site_daily (
    day date primary key,

    -- Distinct sessions. NOT the sum of the per page table.
    visits integer not null default 0,
    -- Distinct visitor hashes. Separates ten people looking once from one
    -- person looking ten times.
    visitors integer not null default 0,
    page_views integer not null default 0,

    -- The MIDDLE stay, never the average. One tab left open over lunch drags an
    -- average into fiction; it moves the median by one row.
    median_dwell_ms integer,

    -- Sessions that read one page and left almost straight away.
    bounced integer not null default 0,

    -- How many bot views were thrown out to get the figures above. Recorded so
    -- the panel can say what it excluded rather than quietly excluding it.
    bot_views integer not null default 0,

    -- Counted on each session's FIRST view, because that is where somebody came
    -- from. Counting every view would credit the channel four times for a visit
    -- that read four pages.
    channels jsonb not null default '{}'::jsonb,
    devices jsonb not null default '{}'::jsonb,

    rolled_at timestamptz not null default timezone('utc', now())
  );

  -- ── the same day, per page ────────────────────────────────────────────────
  create table if not exists public.pcd_site_page_daily (
    day date not null,
    path text not null,
    page_views integer not null default 0,
    -- Distinct sessions that reached this page. Safe to compare between pages,
    -- never safe to add up.
    visits integer not null default 0,
    median_dwell_ms integer,
    primary key (day, path)
  );

  create index if not exists pcd_site_page_daily_day_idx
    on public.pcd_site_page_daily (day);

  -- ── nobody but the server gets in ─────────────────────────────────────────
  --
  -- The write route and the dashboard both use the service role, which bypasses
  -- RLS. No policy grants anybody else a way in, which is deliberate: the anon
  -- key is in the browser on every page of the public site, and a table of who
  -- visited what must not be readable with it.
  alter table public.pcd_site_events enable row level security;
  alter table public.pcd_site_daily enable row level security;
  alter table public.pcd_site_page_daily enable row level security;

  if not exists (
    select 1 from pg_policies
     where schemaname = 'public' and tablename = 'pcd_site_events'
       and policyname = 'pcd_site_events_service_role'
  ) then
    create policy pcd_site_events_service_role
      on public.pcd_site_events for all to authenticated
      using (false) with check (false);
  end if;

  if not exists (
    select 1 from pg_policies
     where schemaname = 'public' and tablename = 'pcd_site_daily'
       and policyname = 'pcd_site_daily_service_role'
  ) then
    create policy pcd_site_daily_service_role
      on public.pcd_site_daily for all to authenticated
      using (false) with check (false);
  end if;

  if not exists (
    select 1 from pg_policies
     where schemaname = 'public' and tablename = 'pcd_site_page_daily'
       and policyname = 'pcd_site_page_daily_service_role'
  ) then
    create policy pcd_site_page_daily_service_role
      on public.pcd_site_page_daily for all to authenticated
      using (false) with check (false);
  end if;

  comment on table public.pcd_site_events is
    'One row per page view on the public site. No IP, no user agent, no person. Pruned after 90 days by /api/cron/site-rollup.';
  comment on table public.pcd_site_daily is
    'The day rolled up. Visits are distinct sessions and are NOT the sum of pcd_site_page_daily.';
  comment on table public.pcd_site_page_daily is
    'The same day per page. Page views add up across pages; visits do not.';

  raise notice 'Site traffic tables ready. Set SITE_TRACKING_SALT in the environment before this collects anything.';

end $$;

notify pgrst, 'reload schema';
