-- Generated from C:\Users\Ashle\Downloads\allproducts.xlsx
-- Inserts unique Polytec board-supply colour library rows for 16mm/18mm decorative board and compact laminate.
-- Image fields and costs are intentionally left blank/defaulted.

begin;

with input_rows (supplier_name, material_type, thickness, finish_type, name, order_type, order_types, is_active, sort_order) as (
  values
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Black', 'supply board', array['supply board']::text[], true, 1),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Blossom White', 'supply board', array['supply board']::text[], true, 2),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Cinder', 'supply board', array['supply board']::text[], true, 3),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Natural Oak', 'supply board', array['supply board']::text[], true, 4),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Nickel', 'supply board', array['supply board']::text[], true, 5),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Nouveau Grey', 'supply board', array['supply board']::text[], true, 6),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Oyster Grey', 'supply board', array['supply board']::text[], true, 7),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Polar White', 'supply board', array['supply board']::text[], true, 8),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Prime Oak', 'supply board', array['supply board']::text[], true, 9),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Stone Grey', 'supply board', array['supply board']::text[], true, 10),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Storm', 'supply board', array['supply board']::text[], true, 11),
  ('Polytec', 'compact laminate', '13mm', 'Matt', 'Titanium', 'supply board', array['supply board']::text[], true, 12),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Agave', 'supply board', array['supply board']::text[], true, 13),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Alicante Stone', 'supply board', array['supply board']::text[], true, 14),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Aston White', 'supply board', array['supply board']::text[], true, 15),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Athena Stone', 'supply board', array['supply board']::text[], true, 16),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Calacutta D''oro', 'supply board', array['supply board']::text[], true, 17),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Calacutta Grey', 'supply board', array['supply board']::text[], true, 18),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Catalina Marble', 'supply board', array['supply board']::text[], true, 19),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Dark Cement', 'supply board', array['supply board']::text[], true, 20),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Grey Cement', 'supply board', array['supply board']::text[], true, 21),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Habitat', 'supply board', array['supply board']::text[], true, 22),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Marmo di Monte', 'supply board', array['supply board']::text[], true, 23),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Marmo di Torre', 'supply board', array['supply board']::text[], true, 24),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Portland Stone', 'supply board', array['supply board']::text[], true, 25),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Portofino Stone', 'supply board', array['supply board']::text[], true, 26),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Roman Ceppo', 'supply board', array['supply board']::text[], true, 27),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Tivoli Ceppo', 'supply board', array['supply board']::text[], true, 28),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Topiary', 'supply board', array['supply board']::text[], true, 29),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Verdelho', 'supply board', array['supply board']::text[], true, 30),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'Vesuvius Ceppo', 'supply board', array['supply board']::text[], true, 31),
  ('Polytec', 'compact laminate', '13mm', 'Smooth', 'White Cement', 'supply board', array['supply board']::text[], true, 32),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Angora Oak', 'supply board', array['supply board']::text[], true, 33),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Antico Oak', 'supply board', array['supply board']::text[], true, 34),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Australian Native', 'supply board', array['supply board']::text[], true, 35),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Batten Oak', 'supply board', array['supply board']::text[], true, 36),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Black Ply', 'supply board', array['supply board']::text[], true, 37),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Blonde Oak', 'supply board', array['supply board']::text[], true, 38),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Boston Oak', 'supply board', array['supply board']::text[], true, 39),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Botany Oak', 'supply board', array['supply board']::text[], true, 40),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Bottega Oak', 'supply board', array['supply board']::text[], true, 41),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Bronzed Oak', 'supply board', array['supply board']::text[], true, 42),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Casentino Beech', 'supply board', array['supply board']::text[], true, 43),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Dark Batten Oak', 'supply board', array['supply board']::text[], true, 44),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'District Oak', 'supply board', array['supply board']::text[], true, 45),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Empire Oak', 'supply board', array['supply board']::text[], true, 46),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Florentine Walnut', 'supply board', array['supply board']::text[], true, 47),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Manor Oak', 'supply board', array['supply board']::text[], true, 48),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Natural Ply', 'supply board', array['supply board']::text[], true, 49),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Notaio Walnut', 'supply board', array['supply board']::text[], true, 50),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Perugian Walnut', 'supply board', array['supply board']::text[], true, 51),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Prime Oak', 'supply board', array['supply board']::text[], true, 52),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Society Oak', 'supply board', array['supply board']::text[], true, 53),
  ('Polytec', 'compact laminate', '13mm', 'Woodmatt', 'Tasmanian Oak', 'supply board', array['supply board']::text[], true, 54),
  ('Polytec', 'compact laminate', '18mm', 'Matt', 'Black', 'supply board', array['supply board']::text[], true, 55),
  ('Polytec', 'compact laminate', '18mm', 'Matt', 'Oyster Grey', 'supply board', array['supply board']::text[], true, 56),
  ('Polytec', 'compact laminate', '18mm', 'Matt', 'Polar White', 'supply board', array['supply board']::text[], true, 57),
  ('Polytec', 'compact laminate', '5mm', 'Matt', 'Black', 'supply board', array['supply board']::text[], true, 58),
  ('Polytec', 'compact laminate', '5mm', 'Matt', 'Blossom White', 'supply board', array['supply board']::text[], true, 59),
  ('Polytec', 'compact laminate', '5mm', 'Matt', 'Cinder', 'supply board', array['supply board']::text[], true, 60),
  ('Polytec', 'compact laminate', '5mm', 'Matt', 'Natural Oak', 'supply board', array['supply board']::text[], true, 61),
  ('Polytec', 'compact laminate', '5mm', 'Matt', 'Nouveau Grey', 'supply board', array['supply board']::text[], true, 62),
  ('Polytec', 'compact laminate', '5mm', 'Matt', 'Polar White', 'supply board', array['supply board']::text[], true, 63),
  ('Polytec', 'compact laminate', '5mm', 'Matt', 'Stone Grey', 'supply board', array['supply board']::text[], true, 64),
  ('Polytec', 'compact laminate', '5mm', 'Smooth', 'Athena Stone', 'supply board', array['supply board']::text[], true, 65),
  ('Polytec', 'compact laminate', '5mm', 'Smooth', 'Calacutta D''oro', 'supply board', array['supply board']::text[], true, 66),
  ('Polytec', 'compact laminate', '5mm', 'Smooth', 'Calacutta Grey', 'supply board', array['supply board']::text[], true, 67),
  ('Polytec', 'compact laminate', '5mm', 'Smooth', 'Catalina Marble', 'supply board', array['supply board']::text[], true, 68),
  ('Polytec', 'compact laminate', '5mm', 'Smooth', 'Dark Cement', 'supply board', array['supply board']::text[], true, 69),
  ('Polytec', 'compact laminate', '5mm', 'Smooth', 'Grey Cement', 'supply board', array['supply board']::text[], true, 70),
  ('Polytec', 'compact laminate', '5mm', 'Smooth', 'Portland Stone', 'supply board', array['supply board']::text[], true, 71),
  ('Polytec', 'compact laminate', '5mm', 'Smooth', 'Portofino Stone', 'supply board', array['supply board']::text[], true, 72),
  ('Polytec', 'compact laminate', '5mm', 'Smooth', 'White Cement', 'supply board', array['supply board']::text[], true, 73),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Antico Oak', 'supply board', array['supply board']::text[], true, 74),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Australian Native', 'supply board', array['supply board']::text[], true, 75),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Batten Oak', 'supply board', array['supply board']::text[], true, 76),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Blonde Oak', 'supply board', array['supply board']::text[], true, 77),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Boston Oak', 'supply board', array['supply board']::text[], true, 78),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Botany Oak', 'supply board', array['supply board']::text[], true, 79),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Bronzed Oak', 'supply board', array['supply board']::text[], true, 80),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Dark Batten Oak', 'supply board', array['supply board']::text[], true, 81),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'District Oak', 'supply board', array['supply board']::text[], true, 82),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Empire Oak', 'supply board', array['supply board']::text[], true, 83),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Manor Oak', 'supply board', array['supply board']::text[], true, 84),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Notaio Walnut', 'supply board', array['supply board']::text[], true, 85),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Prime Oak', 'supply board', array['supply board']::text[], true, 86),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Society Oak', 'supply board', array['supply board']::text[], true, 87),
  ('Polytec', 'compact laminate', '5mm', 'Woodmatt', 'Tasmanian Oak', 'supply board', array['supply board']::text[], true, 88),
  ('Polytec', 'decorative board', '16mm', 'Ashgrain', 'Classic White', 'supply board', array['supply board']::text[], true, 89),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Alabaster', 'supply board', array['supply board']::text[], true, 90),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Aluminium', 'supply board', array['supply board']::text[], true, 91),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Amaro', 'supply board', array['supply board']::text[], true, 92),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Antique', 'supply board', array['supply board']::text[], true, 93),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Artisan Oak', 'supply board', array['supply board']::text[], true, 94),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Avion Grey', 'supply board', array['supply board']::text[], true, 95),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Belgian Oak', 'supply board', array['supply board']::text[], true, 96),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Black', 'supply board', array['supply board']::text[], true, 97),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Black Wenge', 'supply board', array['supply board']::text[], true, 98),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Blossom White', 'supply board', array['supply board']::text[], true, 99),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Bronze Gold Leaf', 'supply board', array['supply board']::text[], true, 100),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Cafe Cream', 'supply board', array['supply board']::text[], true, 101),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Canterbury Grey', 'supply board', array['supply board']::text[], true, 102),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Carcass', 'supply board', array['supply board']::text[], true, 103),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Cavia Lini', 'supply board', array['supply board']::text[], true, 104),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Char Oak', 'supply board', array['supply board']::text[], true, 105),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Cinder', 'supply board', array['supply board']::text[], true, 106),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Classic White', 'supply board', array['supply board']::text[], true, 107),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Combat Teak', 'supply board', array['supply board']::text[], true, 108),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Copper Leaf', 'supply board', array['supply board']::text[], true, 109),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Crema Lini', 'supply board', array['supply board']::text[], true, 110),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Empire Oak', 'supply board', array['supply board']::text[], true, 111),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'European Walnut', 'supply board', array['supply board']::text[], true, 112),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Feldspar Shimmer', 'supply board', array['supply board']::text[], true, 113),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Ferro', 'supply board', array['supply board']::text[], true, 114),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Gesso Lini', 'supply board', array['supply board']::text[], true, 115),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Graphite', 'supply board', array['supply board']::text[], true, 116),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Greige', 'supply board', array['supply board']::text[], true, 117),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Husk', 'supply board', array['supply board']::text[], true, 118),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Italian Cotton', 'supply board', array['supply board']::text[], true, 119),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Jamaican Walnut', 'supply board', array['supply board']::text[], true, 120),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Light Brass Leaf', 'supply board', array['supply board']::text[], true, 121),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Maison Oak', 'supply board', array['supply board']::text[], true, 122),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Malt', 'supply board', array['supply board']::text[], true, 123),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Marina Grey', 'supply board', array['supply board']::text[], true, 124),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Marni Lini', 'supply board', array['supply board']::text[], true, 125),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Moss Grey', 'supply board', array['supply board']::text[], true, 126),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Natural Cotton', 'supply board', array['supply board']::text[], true, 127),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Natural Oak', 'supply board', array['supply board']::text[], true, 128),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'New Antique White', 'supply board', array['supply board']::text[], true, 129),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Nickel', 'supply board', array['supply board']::text[], true, 130),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Notaio Walnut', 'supply board', array['supply board']::text[], true, 131),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Nouveau Grey', 'supply board', array['supply board']::text[], true, 132),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Oxford', 'supply board', array['supply board']::text[], true, 133),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Oyster Grey', 'supply board', array['supply board']::text[], true, 134),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Parchment', 'supply board', array['supply board']::text[], true, 135),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Platinum Leaf', 'supply board', array['supply board']::text[], true, 136),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Polar White', 'supply board', array['supply board']::text[], true, 137),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Porcelain', 'supply board', array['supply board']::text[], true, 138),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Prime Oak', 'supply board', array['supply board']::text[], true, 139),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Pure Gold Leaf', 'supply board', array['supply board']::text[], true, 140),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Rocco Lini', 'supply board', array['supply board']::text[], true, 141),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Rose Gold Leaf', 'supply board', array['supply board']::text[], true, 142),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Shannon Oak', 'supply board', array['supply board']::text[], true, 143),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Silk', 'supply board', array['supply board']::text[], true, 144),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Soft Walnut', 'supply board', array['supply board']::text[], true, 145),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Stone Grey', 'supply board', array['supply board']::text[], true, 146),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Strata Grey', 'supply board', array['supply board']::text[], true, 147),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Tasmanian Oak', 'supply board', array['supply board']::text[], true, 148),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Taupe', 'supply board', array['supply board']::text[], true, 149),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Tessuto Milan', 'supply board', array['supply board']::text[], true, 150),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Titanium', 'supply board', array['supply board']::text[], true, 151),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Truffle Lini', 'supply board', array['supply board']::text[], true, 152),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Tuross Oak', 'supply board', array['supply board']::text[], true, 153),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'White Cotton', 'supply board', array['supply board']::text[], true, 154),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'White Mist', 'supply board', array['supply board']::text[], true, 155),
  ('Polytec', 'decorative board', '16mm', 'Matt', 'Whitewood', 'supply board', array['supply board']::text[], true, 156),
  ('Polytec', 'decorative board', '16mm', 'Satin', 'Carcass', 'supply board', array['supply board']::text[], true, 157),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Alabaster', 'supply board', array['supply board']::text[], true, 158),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Amaro', 'supply board', array['supply board']::text[], true, 159),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Blossom White', 'supply board', array['supply board']::text[], true, 160),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Cavia Lini', 'supply board', array['supply board']::text[], true, 161),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Classic White', 'supply board', array['supply board']::text[], true, 162),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Moss Grey', 'supply board', array['supply board']::text[], true, 163),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Polar White', 'supply board', array['supply board']::text[], true, 164),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Porcelain', 'supply board', array['supply board']::text[], true, 165),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Stone Grey', 'supply board', array['supply board']::text[], true, 166),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Strata Grey', 'supply board', array['supply board']::text[], true, 167),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'Truffle Lini', 'supply board', array['supply board']::text[], true, 168),
  ('Polytec', 'decorative board', '16mm', 'Sheen', 'White Mist', 'supply board', array['supply board']::text[], true, 169),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Adriatic', 'supply board', array['supply board']::text[], true, 170),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Agave', 'supply board', array['supply board']::text[], true, 171),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Arabica', 'supply board', array['supply board']::text[], true, 172),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Aston White', 'supply board', array['supply board']::text[], true, 173),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Botanic', 'supply board', array['supply board']::text[], true, 174),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Elemental Grey', 'supply board', array['supply board']::text[], true, 175),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Forage', 'supply board', array['supply board']::text[], true, 176),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Gossamer White', 'supply board', array['supply board']::text[], true, 177),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Habitat', 'supply board', array['supply board']::text[], true, 178),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Mercurio Grey', 'supply board', array['supply board']::text[], true, 179),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Oasis', 'supply board', array['supply board']::text[], true, 180),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Ochre Figured-Wood', 'supply board', array['supply board']::text[], true, 181),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Onyx Figured-Wood', 'supply board', array['supply board']::text[], true, 182),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Pallido', 'supply board', array['supply board']::text[], true, 183),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Sienna Figured-Wood', 'supply board', array['supply board']::text[], true, 184),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Topiary', 'supply board', array['supply board']::text[], true, 185),
  ('Polytec', 'decorative board', '16mm', 'Smooth', 'Verdelho', 'supply board', array['supply board']::text[], true, 186),
  ('Polytec', 'decorative board', '16mm', 'Texture', 'Black', 'supply board', array['supply board']::text[], true, 187),
  ('Polytec', 'decorative board', '16mm', 'Texture', 'Carcass', 'supply board', array['supply board']::text[], true, 188),
  ('Polytec', 'decorative board', '16mm', 'Texture', 'Classic White', 'supply board', array['supply board']::text[], true, 189),
  ('Polytec', 'decorative board', '16mm', 'Texture', 'Designer White', 'supply board', array['supply board']::text[], true, 190),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Angora Oak', 'supply board', array['supply board']::text[], true, 191),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Antico Oak', 'supply board', array['supply board']::text[], true, 192),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Arcadia Oak', 'supply board', array['supply board']::text[], true, 193),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Australian Native', 'supply board', array['supply board']::text[], true, 194),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Bespoke', 'supply board', array['supply board']::text[], true, 195),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Black', 'supply board', array['supply board']::text[], true, 196),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Black Ply', 'supply board', array['supply board']::text[], true, 197),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Blossom White', 'supply board', array['supply board']::text[], true, 198),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Boston Oak', 'supply board', array['supply board']::text[], true, 199),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Bottega Oak', 'supply board', array['supply board']::text[], true, 200),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Casentino Beech', 'supply board', array['supply board']::text[], true, 201),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Cinder', 'supply board', array['supply board']::text[], true, 202),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Coastal Oak', 'supply board', array['supply board']::text[], true, 203),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Empire Oak', 'supply board', array['supply board']::text[], true, 204),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Estella Oak', 'supply board', array['supply board']::text[], true, 205),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Florentine Walnut', 'supply board', array['supply board']::text[], true, 206),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Havana Oak', 'supply board', array['supply board']::text[], true, 207),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Ligurian Walnut', 'supply board', array['supply board']::text[], true, 208),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Natural Ply', 'supply board', array['supply board']::text[], true, 209),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Nordic Oak', 'supply board', array['supply board']::text[], true, 210),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Notaio Walnut', 'supply board', array['supply board']::text[], true, 211),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Palace Teak', 'supply board', array['supply board']::text[], true, 212),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Palomera Oak', 'supply board', array['supply board']::text[], true, 213),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Perugian Walnut', 'supply board', array['supply board']::text[], true, 214),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Plantation Ash', 'supply board', array['supply board']::text[], true, 215),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Prime Oak', 'supply board', array['supply board']::text[], true, 216),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Quartiera Maple', 'supply board', array['supply board']::text[], true, 217),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Rojo Walnut', 'supply board', array['supply board']::text[], true, 218),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Serene', 'supply board', array['supply board']::text[], true, 219),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Silk', 'supply board', array['supply board']::text[], true, 220),
  ('Polytec', 'decorative board', '16mm', 'Woodmatt', 'Tasmanian Oak', 'supply board', array['supply board']::text[], true, 221),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Anthracite Metallic', 'supply board', array['supply board']::text[], true, 222),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Arctic Ice', 'supply board', array['supply board']::text[], true, 223),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Black', 'supply board', array['supply board']::text[], true, 224),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Black Wenge', 'supply board', array['supply board']::text[], true, 225),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Cavia Lini', 'supply board', array['supply board']::text[], true, 226),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Champagne Metallic', 'supply board', array['supply board']::text[], true, 227),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Cinder', 'supply board', array['supply board']::text[], true, 228),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Cloudy Grey', 'supply board', array['supply board']::text[], true, 229),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Cream', 'supply board', array['supply board']::text[], true, 230),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Jamaican Walnut', 'supply board', array['supply board']::text[], true, 231),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'New Ultra White', 'supply board', array['supply board']::text[], true, 232),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Ochre Figured-Wood', 'supply board', array['supply board']::text[], true, 233),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Onyx Figured-Wood', 'supply board', array['supply board']::text[], true, 234),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Paris Grey', 'supply board', array['supply board']::text[], true, 235),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Pearl Metallic', 'supply board', array['supply board']::text[], true, 236),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Phantom Black', 'supply board', array['supply board']::text[], true, 237),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Raven Metallic', 'supply board', array['supply board']::text[], true, 238),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Royal Oyster', 'supply board', array['supply board']::text[], true, 239),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Sienna Figured-Wood', 'supply board', array['supply board']::text[], true, 240),
  ('Polytec', 'decorative board', '18mm', 'Gloss', 'Superior White', 'supply board', array['supply board']::text[], true, 241),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Bespoke', 'supply board', array['supply board']::text[], true, 242),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Bleached Walnut', 'supply board', array['supply board']::text[], true, 243),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Bone White', 'supply board', array['supply board']::text[], true, 244),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Castel', 'supply board', array['supply board']::text[], true, 245),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Crisp White', 'supply board', array['supply board']::text[], true, 246),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Drifted Oak', 'supply board', array['supply board']::text[], true, 247),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Grey Cement', 'supply board', array['supply board']::text[], true, 248),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Maison Oak', 'supply board', array['supply board']::text[], true, 249),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Maroso Milan', 'supply board', array['supply board']::text[], true, 250),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Montage', 'supply board', array['supply board']::text[], true, 251),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Papyrus', 'supply board', array['supply board']::text[], true, 252),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Serene', 'supply board', array['supply board']::text[], true, 253),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'Silk', 'supply board', array['supply board']::text[], true, 254),
  ('Polytec', 'decorative board', '18mm', 'Legato', 'White Cement', 'supply board', array['supply board']::text[], true, 255),
  ('Polytec', 'decorative board', '18mm', 'Matt', 'Black', 'supply board', array['supply board']::text[], true, 256),
  ('Polytec', 'decorative board', '18mm', 'Matt', 'Carcass', 'supply board', array['supply board']::text[], true, 257),
  ('Polytec', 'decorative board', '18mm', 'Matt', 'Classic White', 'supply board', array['supply board']::text[], true, 258),
  ('Polytec', 'decorative board', '18mm', 'Matt', 'Polar White', 'supply board', array['supply board']::text[], true, 259),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Artisan Oak', 'supply board', array['supply board']::text[], true, 260),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Avion Grey', 'supply board', array['supply board']::text[], true, 261),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Black Wenge', 'supply board', array['supply board']::text[], true, 262),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Bleached Walnut', 'supply board', array['supply board']::text[], true, 263),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Blossom White', 'supply board', array['supply board']::text[], true, 264),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Cafe Oak', 'supply board', array['supply board']::text[], true, 265),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Canterbury Grey', 'supply board', array['supply board']::text[], true, 266),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Char Oak', 'supply board', array['supply board']::text[], true, 267),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Distressed Wood', 'supply board', array['supply board']::text[], true, 268),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Drifted Oak', 'supply board', array['supply board']::text[], true, 269),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Elemental Grey', 'supply board', array['supply board']::text[], true, 270),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Gossamer White', 'supply board', array['supply board']::text[], true, 271),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Greige', 'supply board', array['supply board']::text[], true, 272),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Maison Oak', 'supply board', array['supply board']::text[], true, 273),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Maroso Milan', 'supply board', array['supply board']::text[], true, 274),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Natural Oak', 'supply board', array['supply board']::text[], true, 275),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Notaio Walnut', 'supply board', array['supply board']::text[], true, 276),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Satra Wood', 'supply board', array['supply board']::text[], true, 277),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Sepia Oak', 'supply board', array['supply board']::text[], true, 278),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Soft Walnut', 'supply board', array['supply board']::text[], true, 279),
  ('Polytec', 'decorative board', '18mm', 'Ravine', 'Tessuto Milan', 'supply board', array['supply board']::text[], true, 280),
  ('Polytec', 'decorative board', '18mm', 'Satin', 'Carcass', 'supply board', array['supply board']::text[], true, 281),
  ('Polytec', 'decorative board', '18mm', 'Sheen', 'Classic White', 'supply board', array['supply board']::text[], true, 282),
  ('Polytec', 'decorative board', '18mm', 'Sheen', 'Polar White', 'supply board', array['supply board']::text[], true, 283),
  ('Polytec', 'decorative board', '18mm', 'Texture', 'Black', 'supply board', array['supply board']::text[], true, 284),
  ('Polytec', 'decorative board', '18mm', 'Texture', 'Carcass', 'supply board', array['supply board']::text[], true, 285),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'Black', 'supply board', array['supply board']::text[], true, 286),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'Evergreen', 'supply board', array['supply board']::text[], true, 287),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'Jasmine', 'supply board', array['supply board']::text[], true, 288),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'Lava', 'supply board', array['supply board']::text[], true, 289),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'Mineral Metallic', 'supply board', array['supply board']::text[], true, 290),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'Mink', 'supply board', array['supply board']::text[], true, 291),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'Navy', 'supply board', array['supply board']::text[], true, 292),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'Obsidian Metallic', 'supply board', array['supply board']::text[], true, 293),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'Pewter Metallic', 'supply board', array['supply board']::text[], true, 294),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'Sterling', 'supply board', array['supply board']::text[], true, 295),
  ('Polytec', 'decorative board', '18mm', 'Ultramatt', 'White', 'supply board', array['supply board']::text[], true, 296),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Adriatic', 'supply board', array['supply board']::text[], true, 297),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Arabica', 'supply board', array['supply board']::text[], true, 298),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Avion Grey', 'supply board', array['supply board']::text[], true, 299),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Black', 'supply board', array['supply board']::text[], true, 300),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Black Wenge', 'supply board', array['supply board']::text[], true, 301),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Blossom White', 'supply board', array['supply board']::text[], true, 302),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Botanic', 'supply board', array['supply board']::text[], true, 303),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Canterbury Grey', 'supply board', array['supply board']::text[], true, 304),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Cinder', 'supply board', array['supply board']::text[], true, 305),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Ferro', 'supply board', array['supply board']::text[], true, 306),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Forage', 'supply board', array['supply board']::text[], true, 307),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Habitat', 'supply board', array['supply board']::text[], true, 308),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Nouveau Grey', 'supply board', array['supply board']::text[], true, 309),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Oasis', 'supply board', array['supply board']::text[], true, 310),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Oxford', 'supply board', array['supply board']::text[], true, 311),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Topiary', 'supply board', array['supply board']::text[], true, 312),
  ('Polytec', 'decorative board', '18mm', 'Venette', 'Ultra White', 'supply board', array['supply board']::text[], true, 313),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Batten Oak', 'supply board', array['supply board']::text[], true, 314),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Blackened Oak', 'supply board', array['supply board']::text[], true, 315),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Blonde Oak', 'supply board', array['supply board']::text[], true, 316),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Boston Oak', 'supply board', array['supply board']::text[], true, 317),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Botany Oak', 'supply board', array['supply board']::text[], true, 318),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Bronzed Oak', 'supply board', array['supply board']::text[], true, 319),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Danish Rattan', 'supply board', array['supply board']::text[], true, 320),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Dark Batten Oak', 'supply board', array['supply board']::text[], true, 321),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'District Oak', 'supply board', array['supply board']::text[], true, 322),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Ecru Oak', 'supply board', array['supply board']::text[], true, 323),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Hazel Oak', 'supply board', array['supply board']::text[], true, 324),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Laurel Oak', 'supply board', array['supply board']::text[], true, 325),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Manor Oak', 'supply board', array['supply board']::text[], true, 326),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Rubra Oak', 'supply board', array['supply board']::text[], true, 327),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Society Oak', 'supply board', array['supply board']::text[], true, 328),
  ('Polytec', 'decorative board', '18mm', 'Woodmatt', 'Swiss Rattan', 'supply board', array['supply board']::text[], true, 329)
)
insert into public.pcd_colour_library (
  supplier_name,
  material_type,
  thickness,
  finish_type,
  name,
  order_type,
  order_types,
  is_active,
  sort_order
)
select
  supplier_name,
  material_type,
  thickness,
  finish_type,
  name,
  order_type,
  order_types,
  is_active,
  sort_order
from input_rows incoming
where not exists (
  select 1
  from public.pcd_colour_library existing
  where lower(trim(existing.supplier_name)) = lower(trim(incoming.supplier_name))
    and lower(trim(existing.material_type)) = lower(trim(incoming.material_type))
    and lower(trim(coalesce(existing.thickness, ''))) = lower(trim(coalesce(incoming.thickness, '')))
    and lower(trim(existing.finish_type)) = lower(trim(incoming.finish_type))
    and lower(trim(existing.name)) = lower(trim(incoming.name))
);

commit;

-- Unique rows prepared: 329
