create extension if not exists "pgcrypto";

-- Seed generated from C:\Users\Ashle\Downloads\pcd_products.xlsx.
-- Upserts by slug so it can be re-run without deleting unrelated products.

create unique index if not exists idx_products_slug_unique
  on public.products(slug);

insert into public.products (
  id,
  slug,
  category,
  eyebrow,
  name,
  card_title,
  page_title,
  short_description,
  long_description,
  detail_description,
  meta_description,
  cta_label,
  cta_url,
  currency,
  price_from,
  is_active,
  sort_order,
  type,
  type_label,
  material,
  material_label,
  compatibility,
  compatibility_label,
  ikea_system,
  style,
  standard_size,
  hero_caption,
  finish_brand,
  lead_time,
  made_to_measure,
  pre_drilled,
  features,
  finishes,
  gallery_images,
  pricing_rows,
  info_cards,
  related_product_ids,
  product_options
)
values
(
  gen_random_uuid(),
  'cabinet-door-16mm-decorative-board',
  'cabinet-doors',
  'Custom Cabinetry',
  'Cabinet Door – 16mm Decorative Board',
  'Cabinet Door – 16mm Decorative Board',
  'Cabinet Door – 16mm Decorative Board',
  'Made-to-measure cabinet doors in 16mm decorative board. Available in Polytec, Laminex and Formica, with optional hinge drilling. Cut and finished in Perth to your exact dimensions.',
  'Made-to-measure cabinet doors in 16mm decorative board. Available in Polytec, Laminex and Formica, with optional hinge drilling. Cut and finished in Perth to your exact dimensions.',
  'These cabinet doors are cut from 16mm decorative board and finished to order in your choice of Polytec, Laminex or Formica. Every door is made to your exact measurements here in Perth, so what arrives is ready to hang. The 16mm thickness is well suited to overhead cupboards, wall units and lighter upper cabinetry where a slimmer profile keeps things looking clean without compromising on strength. You choose the colour, the finish and the profile, and we take care of everything from there — including hinge drilling if you need it. Jason has over 20 years of cabinet making experience behind every door that leaves the workshop, and that shows in the consistency of the cut, the edge finish and the way each door sits once it''s hung.',
  'Custom cabinet doors in 16mm decorative board, made to measure in Perth WA. Available in Polytec, Laminex and Formica with optional hinge drilling. Order online or request a quote.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  10,
  'door',
  'Cabinet Door',
  '16mm',
  '16mm Decorative Board',
  'all',
  'Custom cabinetry',
  null,
  'Flat slab / profile to order',
  'Made to measure',
  'Precision-cut doors in your choice of Polytec, Laminex or Formica',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – all doors cut to your specified dimensions',
  'Optional – hinge holes available on request',
  '["Made to your exact measurements","Choice of Polytec, Laminex or Formica","Optional hinge drilling","Flat slab or profile available","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["cabinet-door-18mm-decorative-board","cabinet-door-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'cabinet-door-18mm-decorative-board',
  'cabinet-doors',
  'Custom Cabinetry',
  'Cabinet Door – 18mm Decorative Board',
  'Cabinet Door – 18mm Decorative Board',
  'Cabinet Door – 18mm Decorative Board',
  'Made-to-measure cabinet doors in 18mm decorative board. Ideal for lower cabinetry and full-height runs. Available in Polytec, Laminex and Formica, with optional hinge drilling.',
  'Made-to-measure cabinet doors in 18mm decorative board. Ideal for lower cabinetry and full-height runs. Available in Polytec, Laminex and Formica, with optional hinge drilling.',
  'Cut from 18mm decorative board, these cabinet doors are built for applications where you want a little more weight and presence. Lower cabinetry, pantry doors, island cabinet faces and full-height runs all benefit from the extra thickness — the doors sit more solidly on the hinges and the added depth gives edges a more substantial look. Available in the full Polytec, Laminex and Formica range, every door is made to your exact dimensions here in our Perth workshop. Hinge drilling is available on request, and all doors are inspected before they leave to make sure the cut is clean and the finish is consistent. If you''re not sure whether 16mm or 18mm is the right call for your project, get in touch and we''ll point you in the right direction.',
  'Custom cabinet doors in 18mm decorative board, made to measure in Perth WA. Available in Polytec, Laminex and Formica with optional hinge drilling. Request a quote today.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  20,
  'door',
  'Cabinet Door',
  '18mm',
  '18mm Decorative Board',
  'all',
  'Custom cabinetry',
  null,
  'Flat slab / profile to order',
  'Made to measure',
  'Substantial doors with a solid feel, made to your measurements',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – all doors cut to your specified dimensions',
  'Optional – hinge holes available on request',
  '["Made to your exact measurements","Choice of Polytec, Laminex or Formica","Optional hinge drilling","18mm thickness for lower cabinetry and pantry doors","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["cabinet-door-16mm-decorative-board","cabinet-door-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'drawer-front-16mm-decorative-board',
  'drawer-fronts',
  'Custom Cabinetry',
  'Drawer Front – 16mm Decorative Board',
  'Drawer Front – 16mm Decorative Board',
  'Drawer Front – 16mm Decorative Board',
  'Made-to-measure drawer fronts in 16mm decorative board. Available in Polytec, Laminex and Formica. Cut to your exact dimensions and finished consistently with your doors and panels.',
  'Made-to-measure drawer fronts in 16mm decorative board. Available in Polytec, Laminex and Formica. Cut to your exact dimensions and finished consistently with your doors and panels.',
  'Drawer fronts are one of the most noticed details in any kitchen or bathroom, and getting the sizing and finish right makes a real difference to how the whole space looks. These are cut from 16mm decorative board to your exact width and height, available across the full Polytec, Laminex and Formica colour range. The 16mm thickness works well with standard drawer hardware and keeps the overall profile neat — particularly in shallower drawer stacks where every millimetre counts. All fronts are inspected for edge consistency before dispatch, and if you''re ordering alongside doors or panels we can make sure everything comes from the same batch for a consistent finish across the job.',
  'Custom drawer fronts in 16mm decorative board, made to measure in Perth WA. Available in Polytec, Laminex and Formica. Order with matching doors and panels for a consistent finish.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  30,
  'drawer-front',
  'Drawer Front',
  '16mm',
  '16mm Decorative Board',
  'all',
  'Custom cabinetry',
  null,
  'Flat slab / profile to order',
  'Made to measure',
  'Drawer fronts cut to size and finished to match your cabinetry',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – all drawer fronts cut to your specified dimensions',
  null,
  '["Made to your exact measurements","Choice of Polytec, Laminex or Formica","Batch-matched with doors and panels on request","16mm thickness suits standard drawer hardware","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["drawer-front-18mm-decorative-board","drawer-front-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'drawer-front-18mm-decorative-board',
  'drawer-fronts',
  'Custom Cabinetry',
  'Drawer Front – 18mm Decorative Board',
  'Drawer Front – 18mm Decorative Board',
  'Drawer Front – 18mm Decorative Board',
  'Made-to-measure drawer fronts in 18mm decorative board. Available in Polytec, Laminex and Formica. Ideal for use alongside 18mm cabinet doors for a consistent finish throughout.',
  'Made-to-measure drawer fronts in 18mm decorative board. Available in Polytec, Laminex and Formica. Ideal for use alongside 18mm cabinet doors for a consistent finish throughout.',
  'Where you want drawer fronts that feel solid and sit flush with 18mm cabinet carcasses, this is the right choice. Cut from 18mm decorative board to your exact measurements, these fronts are available across the full Polytec, Laminex and Formica range. The extra thickness means the edge profile is more pronounced, which works particularly well in kitchens and laundries where a bolder look is part of the design intent. If you''re combining drawer fronts with 18mm cabinet doors, ordering both together means we can match the batch and keep the finish consistent across the whole run. Get in touch if you''re unsure about sizing or which board thickness suits your existing carcass — we''re happy to help you work it out before you order.',
  'Custom drawer fronts in 18mm decorative board, made to measure in Perth WA. Available in Polytec, Laminex and Formica. Order with matching 18mm doors for a consistent finish.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  40,
  'drawer-front',
  'Drawer Front',
  '18mm',
  '18mm Decorative Board',
  'all',
  'Custom cabinetry',
  null,
  'Flat slab / profile to order',
  'Made to measure',
  'Heavier drawer fronts with a more substantial edge and feel',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – all drawer fronts cut to your specified dimensions',
  null,
  '["Made to your exact measurements","Choice of Polytec, Laminex or Formica","18mm thickness matches standard carcass board","Batch-matched with doors and panels on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["drawer-front-16mm-decorative-board","drawer-front-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'panel-16mm-decorative-board',
  'panels',
  'Custom Cabinetry',
  'Panel – 16mm Decorative Board',
  'Panel – 16mm Decorative Board',
  'Panel – 16mm Decorative Board',
  'Decorative end panels and side returns in 16mm board. Available in Polytec, Laminex and Formica. Made to your dimensions and finished to match your doors and drawer fronts.',
  'Decorative end panels and side returns in 16mm board. Available in Polytec, Laminex and Formica. Made to your dimensions and finished to match your doors and drawer fronts.',
  'Decorative panels in 16mm board are used to finish the visible sides of cabinetry runs — end panels on a kitchen island, side returns on a wall unit, or any face that needs to look intentional rather than like the back of a carcass. Cut to your exact dimensions and available across the full Polytec, Laminex and Formica range, these panels are made in the same Perth workshop as all our doors and drawer fronts, so the finish is consistent when you order everything together. The 16mm thickness suits most wall-hung and overhead applications and keeps the panel from adding unnecessary bulk to narrower spaces. If you have a specific application in mind that needs a custom profile or edge treatment, get in touch and we can talk through what''s possible.',
  'Decorative cabinet panels in 16mm board, made to measure in Perth WA. Available in Polytec, Laminex and Formica. Order with matching doors and drawer fronts.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  50,
  'panel',
  'Panel',
  '16mm',
  '16mm Decorative Board',
  'all',
  'Custom cabinetry',
  null,
  'Flat panel',
  'Made to measure',
  'End panels, side returns and feature walls, cut to size',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – all panels cut to your specified dimensions',
  null,
  '["Made to your exact measurements","Choice of Polytec, Laminex or Formica","Suitable for end panels, side returns and feature walls","Batch-matched with doors and drawer fronts on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the finished width and height you need in millimetres, then send through the application and visible edge details."},{"title":"Panel use","body":"Panels are supplied cut to size and are commonly used for end panels, returns, surrounds and visible cabinet sides."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["panel-18mm-decorative-board","panel-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'panel-18mm-decorative-board',
  'panels',
  'Custom Cabinetry',
  'Panel – 18mm Decorative Board',
  'Panel – 18mm Decorative Board',
  'Panel – 18mm Decorative Board',
  'Decorative end panels and side returns in 18mm board. Available in Polytec, Laminex and Formica. Matches 18mm doors and drawer fronts for a consistent finish across the whole job.',
  'Decorative end panels and side returns in 18mm board. Available in Polytec, Laminex and Formica. Matches 18mm doors and drawer fronts for a consistent finish across the whole job.',
  'When the rest of your cabinetry is built on 18mm board, finishing the visible panels in the same thickness keeps everything proportional and avoids any step at the edges where panels meet doors. These panels are cut from 18mm decorative board to your exact dimensions and are available across the full Polytec, Laminex and Formica colour range. Common applications include island end panels, tall pantry side returns, full-height fridge surrounds and laundry cabinetry where the panel takes some wear. Order alongside your 18mm doors and drawer fronts and we''ll match the batch so the colour and finish are consistent throughout the job.',
  'Decorative cabinet panels in 18mm board, made to measure in Perth WA. Available in Polytec, Laminex and Formica. Matches 18mm doors and drawer fronts throughout.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  60,
  'panel',
  'Panel',
  '18mm',
  '18mm Decorative Board',
  'all',
  'Custom cabinetry',
  null,
  'Flat panel',
  'Made to measure',
  'Solid, substantial panels to finish your cabinetry with confidence',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – all panels cut to your specified dimensions',
  null,
  '["Made to your exact measurements","Choice of Polytec, Laminex or Formica","18mm thickness matches standard carcass construction","Ideal for island ends, fridge surrounds and tall pantry sides","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the finished width and height you need in millimetres, then send through the application and visible edge details."},{"title":"Panel use","body":"Panels are supplied cut to size and are commonly used for end panels, returns, surrounds and visible cabinet sides."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["panel-16mm-decorative-board","panel-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'cabinet-door-thermolaminate',
  'cabinet-doors',
  'Custom Cabinetry',
  'Cabinet Door – Thermolaminate',
  'Cabinet Door – Thermolaminate',
  'Cabinet Door – Thermolaminate',
  'Made-to-measure thermolaminate cabinet doors with a wrapped finish and no visible edge. Full Polytec colour range available. Hinge drilling on request. Made to your dimensions in Perth.',
  'Made-to-measure thermolaminate cabinet doors with a wrapped finish and no visible edge. Full Polytec colour range available. Hinge drilling on request. Made to your dimensions in Perth.',
  'Thermolaminate doors are made by wrapping a decorative film over an MDF substrate under heat and pressure, pulling the finish around all four edges so there''s no raw edge line visible from any angle. The result is a door that looks seamless and feels consistent all the way around — which is why thermolaminate is such a popular choice for kitchens, bathrooms and laundries where the finish needs to hold up and look good from every direction. We offer the full Polytec colour range in thermolaminate, giving you a wide choice of colours and textures — from timber looks and stone-inspired finishes through to clean mattes and high gloss. Every door is made to your exact measurements in our Perth workshop, with hinge drilling available on request. If you''re choosing between thermolaminate and flat decorative board, the wrapped edge of thermolaminate is usually the deciding factor — if the edge is going to be visible in your installation, it''s the cleaner option.',
  'Custom thermolaminate cabinet doors made to measure in Perth WA. Full Polytec colour range, wrapped finish with no visible edge. Optional hinge drilling. Request a quote.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  70,
  'door',
  'Cabinet Door',
  'thermolaminate',
  'Thermolaminate',
  'all',
  'Custom cabinetry',
  null,
  'Flat slab / profile to order',
  'Made to measure',
  'Wrapped doors with no visible edge and a clean finish on every side',
  'Polytec',
  'Enquire for current lead times',
  'Yes – all doors cut to your specified dimensions',
  'Optional – hinge holes available on request',
  '["Wrapped finish with no visible raw edge","Full Polytec colour and texture range","Made to your exact measurements","Optional hinge drilling","MDF substrate for stability","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["cabinet-door-16mm-decorative-board","cabinet-door-18mm-decorative-board"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'drawer-front-thermolaminate',
  'drawer-fronts',
  'Custom Cabinetry',
  'Drawer Front – Thermolaminate',
  'Drawer Front – Thermolaminate',
  'Drawer Front – Thermolaminate',
  'Made-to-measure thermolaminate drawer fronts with a wrapped finish on all four edges. Full Polytec colour range. Order with matching thermolaminate doors for a consistent finish.',
  'Made-to-measure thermolaminate drawer fronts with a wrapped finish on all four edges. Full Polytec colour range. Order with matching thermolaminate doors for a consistent finish.',
  'Thermolaminate drawer fronts bring the same seamless wrapped finish as our thermolaminate doors — the decorative film folds around all four edges, so there''s no edge line visible when a drawer is open or when the front is viewed side-on. This makes a real difference in kitchens and bathrooms where drawers are opened constantly and the edge is always in view. Available across the full Polytec colour and texture range, every front is made to your exact dimensions here in Perth. If you''re ordering drawer fronts alongside thermolaminate doors, we''ll make sure everything comes from the same colour run so the match is consistent across the whole installation.',
  'Custom thermolaminate drawer fronts made to measure in Perth WA. Full Polytec colour range with wrapped finish on all edges. Order with matching thermolaminate doors.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  80,
  'drawer-front',
  'Drawer Front',
  'thermolaminate',
  'Thermolaminate',
  'all',
  'Custom cabinetry',
  null,
  'Flat slab / profile to order',
  'Made to measure',
  'Wrapped drawer fronts that look finished from every angle',
  'Polytec',
  'Enquire for current lead times',
  'Yes – all drawer fronts cut to your specified dimensions',
  null,
  '["Wrapped finish with no visible raw edge","Full Polytec colour and texture range","Made to your exact measurements","Batch-matched with thermolaminate doors on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["drawer-front-16mm-decorative-board","drawer-front-18mm-decorative-board"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'panel-thermolaminate',
  'panels',
  'Custom Cabinetry',
  'Panel – Thermolaminate',
  'Panel – Thermolaminate',
  'Panel – Thermolaminate',
  'Thermolaminate end panels with a fully wrapped finish and no exposed raw edges. Full Polytec colour range. Made to your dimensions and matched to your doors and drawer fronts.',
  'Thermolaminate end panels with a fully wrapped finish and no exposed raw edges. Full Polytec colour range. Made to your dimensions and matched to your doors and drawer fronts.',
  'Thermolaminate panels are used to finish the exposed sides of cabinetry runs where you need the edge to look as considered as the face. Because the film wraps around all four sides, there''s no raw edge or colour-change at the profile — the panel looks finished from every angle, whether it''s an island end, a tall pantry side or a fridge surround. Available across the full Polytec colour and texture range, each panel is made to your exact dimensions in our Perth workshop. Order alongside your thermolaminate doors and drawer fronts and we''ll match the batch so the colour and texture are consistent across the entire installation.',
  'Custom thermolaminate panels made to measure in Perth WA. Fully wrapped finish with no exposed edges. Full Polytec colour range. Order with matching doors and drawer fronts.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  90,
  'panel',
  'Panel',
  'thermolaminate',
  'Thermolaminate',
  'all',
  'Custom cabinetry',
  null,
  'Flat panel',
  'Made to measure',
  'End panels with a fully wrapped finish and no exposed edges',
  'Polytec',
  'Enquire for current lead times',
  'Yes – all panels cut to your specified dimensions',
  null,
  '["Wrapped finish with no exposed raw edges","Full Polytec colour and texture range","Made to your exact measurements","Suitable for island ends, pantry sides and fridge surrounds","Batch-matched with thermolaminate doors on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the finished width and height you need in millimetres, then send through the application and visible edge details."},{"title":"Panel use","body":"Panels are supplied cut to size and are commonly used for end panels, returns, surrounds and visible cabinet sides."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["panel-16mm-decorative-board","panel-18mm-decorative-board"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'ikea-compatible-cabinet-door-16mm-decorative-board',
  'cabinet-doors',
  'IKEA Compatible',
  'IKEA Compatible Cabinet Door – 16mm Decorative Board',
  'IKEA Compatible Cabinet Door – 16mm Decorative Board',
  'IKEA Compatible Cabinet Door – 16mm Decorative Board',
  'Replacement cabinet doors in 16mm decorative board, cut to fit IKEA Metod, Besta and Pax frames. Full Polytec, Laminex and Formica colour range. Pre-drilled to IKEA hinge positions.',
  'Replacement cabinet doors in 16mm decorative board, cut to fit IKEA Metod, Besta and Pax frames. Full Polytec, Laminex and Formica colour range. Pre-drilled to IKEA hinge positions.',
  'IKEA Metod, Besta and Pax frames are genuinely good cabinet carcasses — but the doors that come with them are made to a price point, and the colour and finish options are limited. These replacement doors are cut from 16mm decorative board to the exact dimensions that fit your IKEA frames, and they''re available across the full Polytec, Laminex and Formica colour range. That means you can keep the IKEA carcass you''ve already installed — or are planning to install — and finish the job with doors that look genuinely custom. Hinge holes are drilled to suit standard IKEA hinge positions so fitting is straightforward, and we can supply the hinges if you need them. Whether you''re replacing tired existing doors or spec-ing a new IKEA kitchen with a better finish from the start, this is the most cost-effective way to get a result that looks like it was built from scratch.',
  'Replacement IKEA cabinet doors in 16mm decorative board, made to measure in Perth WA. Fits Metod, Besta and Pax frames. Full Polytec, Laminex and Formica range. Pre-drilled hinge holes.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  100,
  'door',
  'Cabinet Door',
  '16mm',
  '16mm Decorative Board',
  'ikea',
  'IKEA Metod, Besta, Pax',
  'metod, besta, pax',
  'Flat slab / profile to order',
  'Cut to IKEA frame dimensions',
  'Give your IKEA kitchen the custom look it deserves',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified IKEA frame dimensions',
  'Yes – drilled to standard IKEA hinge positions',
  '["Fits IKEA Metod, Besta and Pax frames","Full Polytec, Laminex and Formica colour range","Pre-drilled to standard IKEA hinge positions","Hinges available on request","Made to your exact frame dimensions","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["ikea-compatible-cabinet-door-18mm-decorative-board","ikea-compatible-cabinet-door-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'ikea-compatible-cabinet-door-18mm-decorative-board',
  'cabinet-doors',
  'IKEA Compatible',
  'IKEA Compatible Cabinet Door – 18mm Decorative Board',
  'IKEA Compatible Cabinet Door – 18mm Decorative Board',
  'IKEA Compatible Cabinet Door – 18mm Decorative Board',
  'Replacement cabinet doors in 18mm decorative board, cut to fit IKEA Metod, Besta and Pax frames. Full Polytec, Laminex and Formica colour range. Pre-drilled to IKEA hinge positions.',
  'Replacement cabinet doors in 18mm decorative board, cut to fit IKEA Metod, Besta and Pax frames. Full Polytec, Laminex and Formica colour range. Pre-drilled to IKEA hinge positions.',
  'For those who want a little more weight and solidity in their IKEA replacement doors, the 18mm option delivers. Cut to fit IKEA Metod, Besta and Pax frame dimensions, these doors are made from 18mm decorative board and are available across the full Polytec, Laminex and Formica colour range. The extra thickness is particularly noticeable on larger door panels — pantry doors, tall Pax wardrobe fronts and full-height Metod doors all benefit from the added substance. Hinge holes are drilled to IKEA hinge positions as standard, and we can supply hinges if needed. The result is an IKEA frame finished with doors that feel like they belong in a bespoke kitchen, not a flat-pack one.',
  'Replacement IKEA cabinet doors in 18mm decorative board, made to measure in Perth WA. Fits Metod, Besta and Pax. Full Polytec, Laminex and Formica range. Pre-drilled hinge holes.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  110,
  'door',
  'Cabinet Door',
  '18mm',
  '18mm Decorative Board',
  'ikea',
  'IKEA Metod, Besta, Pax',
  'metod, besta, pax',
  'Flat slab / profile to order',
  'Cut to IKEA frame dimensions',
  'A more substantial door for your IKEA frames',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified IKEA frame dimensions',
  'Yes – drilled to standard IKEA hinge positions',
  '["Fits IKEA Metod, Besta and Pax frames","Full Polytec, Laminex and Formica colour range","Pre-drilled to standard IKEA hinge positions","Hinges available on request","18mm thickness for larger and taller door panels","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["ikea-compatible-cabinet-door-16mm-decorative-board","ikea-compatible-cabinet-door-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'ikea-compatible-drawer-front-16mm-decorative-board',
  'drawer-fronts',
  'IKEA Compatible',
  'IKEA Compatible Drawer Front – 16mm Decorative Board',
  'IKEA Compatible Drawer Front – 16mm Decorative Board',
  'IKEA Compatible Drawer Front – 16mm Decorative Board',
  'Replacement drawer fronts in 16mm decorative board, cut to fit IKEA Metod and Besta drawer openings. Full Polytec, Laminex and Formica colour range.',
  'Replacement drawer fronts in 16mm decorative board, cut to fit IKEA Metod and Besta drawer openings. Full Polytec, Laminex and Formica colour range.',
  'IKEA drawer fronts are one of the easiest things to replace — and one of the most impactful. These replacement fronts are cut from 16mm decorative board to fit standard IKEA Metod and Besta drawer openings, and they''re available in the full Polytec, Laminex and Formica colour range so you''re not stuck with what IKEA stocks. If you''re refreshing an existing IKEA kitchen or speccing a new one with a better finish from day one, swapping the drawer fronts is one of the highest-value changes you can make. Order alongside matching cabinet doors and end panels for a consistent look throughout, and we''ll make sure everything comes from the same colour run.',
  'Replacement IKEA drawer fronts in 16mm decorative board, made to measure in Perth WA. Fits Metod and Besta. Full Polytec, Laminex and Formica colour range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  120,
  'drawer-front',
  'Drawer Front',
  '16mm',
  '16mm Decorative Board',
  'ikea',
  'IKEA Metod, Besta',
  'metod, besta',
  'Flat slab / profile to order',
  'Cut to IKEA drawer dimensions',
  'Upgrade your IKEA drawer fronts without replacing the whole kitchen',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified IKEA drawer dimensions',
  null,
  '["Fits IKEA Metod and Besta drawer openings","Full Polytec, Laminex and Formica colour range","Batch-matched with doors and panels on request","16mm thickness suits IKEA drawer hardware","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["ikea-compatible-drawer-front-18mm-decorative-board","ikea-compatible-drawer-front-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'ikea-compatible-drawer-front-18mm-decorative-board',
  'drawer-fronts',
  'IKEA Compatible',
  'IKEA Compatible Drawer Front – 18mm Decorative Board',
  'IKEA Compatible Drawer Front – 18mm Decorative Board',
  'IKEA Compatible Drawer Front – 18mm Decorative Board',
  'Replacement drawer fronts in 18mm decorative board, cut to fit IKEA Metod and Besta drawer openings. Full Polytec, Laminex and Formica colour range. Order with matching 18mm doors for consistency.',
  'Replacement drawer fronts in 18mm decorative board, cut to fit IKEA Metod and Besta drawer openings. Full Polytec, Laminex and Formica colour range. Order with matching 18mm doors for consistency.',
  'If you''re going to the trouble of upgrading your IKEA drawer fronts, it''s worth considering whether a heavier board gives you the feel you''re after. These fronts are cut from 18mm decorative board to fit standard IKEA Metod and Besta drawer openings, and are available across the full Polytec, Laminex and Formica colour range. The extra thickness adds noticeable weight and presence — particularly on wider drawer fronts where the additional mass makes them feel more considered and less like a component. Order with matching 18mm cabinet doors and panels for a consistent finish across the whole kitchen or cabinetry run.',
  'Replacement IKEA drawer fronts in 18mm decorative board, made to measure in Perth WA. Fits Metod and Besta. Full Polytec, Laminex and Formica range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  130,
  'drawer-front',
  'Drawer Front',
  '18mm',
  '18mm Decorative Board',
  'ikea',
  'IKEA Metod, Besta',
  'metod, besta',
  'Flat slab / profile to order',
  'Cut to IKEA drawer dimensions',
  'Heavier drawer fronts with a more premium feel for IKEA frames',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified IKEA drawer dimensions',
  null,
  '["Fits IKEA Metod and Besta drawer openings","Full Polytec, Laminex and Formica colour range","18mm thickness for added weight and presence","Batch-matched with 18mm doors and panels on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["ikea-compatible-drawer-front-16mm-decorative-board","ikea-compatible-drawer-front-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'ikea-compatible-panel-16mm-decorative-board',
  'panels',
  'IKEA Compatible',
  'IKEA Compatible Panel – 16mm Decorative Board',
  'IKEA Compatible Panel – 16mm Decorative Board',
  'IKEA Compatible Panel – 16mm Decorative Board',
  'End panels in 16mm decorative board, cut to work with IKEA Metod, Besta and Pax. Full Polytec, Laminex and Formica colour range. Order with matching doors and drawer fronts.',
  'End panels in 16mm decorative board, cut to work with IKEA Metod, Besta and Pax. Full Polytec, Laminex and Formica colour range. Order with matching doors and drawer fronts.',
  'IKEA carcasses are designed to sit flush against walls and other units — but where a side is exposed, you need a panel that looks intentional. These replacement end panels are cut from 16mm decorative board to dimensions that work with IKEA Metod, Besta and Pax frames, and are available across the full Polytec, Laminex and Formica colour range. Whether it''s a kitchen island with an exposed end, a Besta unit sitting proud of the wall, or a Pax wardrobe run where the outer side is visible, the right panel makes the whole installation look deliberate rather than unfinished. Order with matching doors and drawer fronts and we''ll make sure the colour is consistent across every piece.',
  'Replacement IKEA end panels in 16mm decorative board, made to measure in Perth WA. Fits Metod, Besta and Pax. Full Polytec, Laminex and Formica range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  140,
  'panel',
  'Panel',
  '16mm',
  '16mm Decorative Board',
  'ikea',
  'IKEA Metod, Besta, Pax',
  'metod, besta, pax',
  'Flat panel',
  'Cut to IKEA frame dimensions',
  'Finish the sides of your IKEA kitchen properly',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified dimensions',
  null,
  '["Works with IKEA Metod, Besta and Pax frames","Full Polytec, Laminex and Formica colour range","Batch-matched with doors and drawer fronts on request","Suitable for exposed island ends and outer frame sides","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the finished width and height you need in millimetres, then send through the application and visible edge details."},{"title":"Panel use","body":"Panels are supplied cut to size and are commonly used for end panels, returns, surrounds and visible cabinet sides."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["ikea-compatible-panel-18mm-decorative-board","ikea-compatible-panel-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'ikea-compatible-panel-18mm-decorative-board',
  'panels',
  'IKEA Compatible',
  'IKEA Compatible Panel – 18mm Decorative Board',
  'IKEA Compatible Panel – 18mm Decorative Board',
  'IKEA Compatible Panel – 18mm Decorative Board',
  'End panels in 18mm decorative board, cut to work with IKEA Metod, Besta and Pax. Full Polytec, Laminex and Formica colour range. Matches 18mm doors and drawer fronts.',
  'End panels in 18mm decorative board, cut to work with IKEA Metod, Besta and Pax. Full Polytec, Laminex and Formica colour range. Matches 18mm doors and drawer fronts.',
  'Where you want the side panels of your IKEA installation to feel as substantial as the rest of the cabinetry, 18mm decorative board is the right choice. These panels are cut to work with IKEA Metod, Besta and Pax frame dimensions and are available across the full Polytec, Laminex and Formica colour range. The extra thickness is particularly relevant on larger exposed sides — a full-height Metod pantry end panel or a wide Besta run where the side is a genuine feature of the space. Order alongside your 18mm doors and drawer fronts and we''ll batch-match the colour so everything sits consistently together.',
  'Replacement IKEA end panels in 18mm decorative board, made to measure in Perth WA. Fits Metod, Besta and Pax. Full Polytec, Laminex and Formica range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  150,
  'panel',
  'Panel',
  '18mm',
  '18mm Decorative Board',
  'ikea',
  'IKEA Metod, Besta, Pax',
  'metod, besta, pax',
  'Flat panel',
  'Cut to IKEA frame dimensions',
  'Substantial end panels that give your IKEA installation a custom feel',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified dimensions',
  null,
  '["Works with IKEA Metod, Besta and Pax frames","Full Polytec, Laminex and Formica colour range","18mm thickness for full-height and feature panel applications","Batch-matched with 18mm doors and drawer fronts on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the finished width and height you need in millimetres, then send through the application and visible edge details."},{"title":"Panel use","body":"Panels are supplied cut to size and are commonly used for end panels, returns, surrounds and visible cabinet sides."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["ikea-compatible-panel-16mm-decorative-board","ikea-compatible-panel-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'ikea-compatible-cabinet-door-thermolaminate',
  'cabinet-doors',
  'IKEA Compatible',
  'IKEA Compatible Cabinet Door – Thermolaminate',
  'IKEA Compatible Cabinet Door – Thermolaminate',
  'IKEA Compatible Cabinet Door – Thermolaminate',
  'Thermolaminate replacement doors for IKEA Metod, Besta and Pax. Wrapped finish on all edges, full Polytec colour range, pre-drilled to IKEA hinge positions.',
  'Thermolaminate replacement doors for IKEA Metod, Besta and Pax. Wrapped finish on all edges, full Polytec colour range, pre-drilled to IKEA hinge positions.',
  'Thermolaminate replacement doors for IKEA Metod, Besta and Pax frames combine the practicality of the IKEA carcass system with a finish that looks like it was never flat-pack at all. The thermolaminate process wraps the decorative film around all four edges of each door, so there''s no visible raw edge from any angle. Combined with the full Polytec colour and texture range — including timber-look, stone-inspired, matte and gloss finishes — the result is an IKEA kitchen that genuinely looks custom. Hinge holes are drilled to standard IKEA hinge positions, and hinges are available if you need them. If you''re planning a full kitchen replacement or upgrade and want the cost efficiency of IKEA frames with a finish that doesn''t look like it, this is the product to start with.',
  'Thermolaminate replacement doors for IKEA Metod, Besta and Pax, made to measure in Perth WA. Wrapped finish, full Polytec colour range, pre-drilled hinge holes. Request a quote.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  160,
  'door',
  'Cabinet Door',
  'thermolaminate',
  'Thermolaminate',
  'ikea',
  'IKEA Metod, Besta, Pax',
  'metod, besta, pax',
  'Flat slab / profile to order',
  'Cut to IKEA frame dimensions',
  'A seamless wrapped finish for your IKEA kitchen upgrade',
  'Polytec',
  'Enquire for current lead times',
  'Yes – cut to your specified IKEA frame dimensions',
  'Yes – drilled to standard IKEA hinge positions',
  '["Fits IKEA Metod, Besta and Pax frames","Wrapped finish with no visible raw edge","Full Polytec colour and texture range","Pre-drilled to IKEA hinge positions","Hinges available on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["ikea-compatible-cabinet-door-16mm-decorative-board","ikea-compatible-cabinet-door-18mm-decorative-board"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'ikea-compatible-drawer-front-thermolaminate',
  'drawer-fronts',
  'IKEA Compatible',
  'IKEA Compatible Drawer Front – Thermolaminate',
  'IKEA Compatible Drawer Front – Thermolaminate',
  'IKEA Compatible Drawer Front – Thermolaminate',
  'Thermolaminate replacement drawer fronts for IKEA Metod and Besta. Wrapped finish on all edges, full Polytec colour range. Order with matching thermolaminate doors for a consistent result.',
  'Thermolaminate replacement drawer fronts for IKEA Metod and Besta. Wrapped finish on all edges, full Polytec colour range. Order with matching thermolaminate doors for a consistent result.',
  'Replacing IKEA drawer fronts with thermolaminate versions is one of the most effective upgrades you can make to an existing or new IKEA kitchen. The wrapped finish means the film covers all four edges, so when a drawer is open or the front is viewed from the side, there''s no raw edge visible — just a clean, consistent finish all the way around. Available in the full Polytec colour and texture range to fit standard IKEA Metod and Besta drawer openings, every front is made to your dimensions here in Perth. Order alongside matching thermolaminate doors and panels for a cohesive result across the whole installation.',
  'Thermolaminate replacement IKEA drawer fronts, made to measure in Perth WA. Fits Metod and Besta. Wrapped finish, full Polytec colour range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  170,
  'drawer-front',
  'Drawer Front',
  'thermolaminate',
  'Thermolaminate',
  'ikea',
  'IKEA Metod, Besta',
  'metod, besta',
  'Flat slab / profile to order',
  'Cut to IKEA drawer dimensions',
  'Thermolaminate drawer fronts that make your IKEA kitchen look the part',
  'Polytec',
  'Enquire for current lead times',
  'Yes – cut to your specified IKEA drawer dimensions',
  null,
  '["Fits IKEA Metod and Besta drawer openings","Wrapped finish with no visible raw edge","Full Polytec colour and texture range","Batch-matched with thermolaminate doors and panels on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["ikea-compatible-drawer-front-16mm-decorative-board","ikea-compatible-drawer-front-18mm-decorative-board"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'ikea-compatible-panel-thermolaminate',
  'panels',
  'IKEA Compatible',
  'IKEA Compatible Panel – Thermolaminate',
  'IKEA Compatible Panel – Thermolaminate',
  'IKEA Compatible Panel – Thermolaminate',
  'Thermolaminate end panels for IKEA Metod, Besta and Pax. Wrapped finish on all edges, full Polytec colour range. Matched to your thermolaminate doors and drawer fronts.',
  'Thermolaminate end panels for IKEA Metod, Besta and Pax. Wrapped finish on all edges, full Polytec colour range. Matched to your thermolaminate doors and drawer fronts.',
  'When the end or side of an IKEA cabinet run is on show, a thermolaminate panel is the cleanest way to finish it. The wrapped film covers all four edges, so the panel looks complete from every angle — not just from the front. These panels are made to dimensions that work with IKEA Metod, Besta and Pax frames, and are available across the full Polytec colour and texture range. Whether it''s an island end, a tall unit side or an exposed Pax wardrobe edge, the right panel ties the whole installation together. Order alongside your thermolaminate doors and drawer fronts and we''ll make sure everything is matched from the same colour run.',
  'Thermolaminate IKEA end panels made to measure in Perth WA. Fits Metod, Besta and Pax. Wrapped finish, full Polytec colour range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  180,
  'panel',
  'Panel',
  'thermolaminate',
  'Thermolaminate',
  'ikea',
  'IKEA Metod, Besta, Pax',
  'metod, besta, pax',
  'Flat panel',
  'Cut to IKEA frame dimensions',
  'Wrap the exposed sides of your IKEA installation in a seamless finish',
  'Polytec',
  'Enquire for current lead times',
  'Yes – cut to your specified dimensions',
  null,
  '["Works with IKEA Metod, Besta and Pax frames","Wrapped finish with no visible raw edge","Full Polytec colour and texture range","Batch-matched with thermolaminate doors and drawer fronts on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the finished width and height you need in millimetres, then send through the application and visible edge details."},{"title":"Panel use","body":"Panels are supplied cut to size and are commonly used for end panels, returns, surrounds and visible cabinet sides."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["ikea-compatible-panel-16mm-decorative-board","ikea-compatible-panel-18mm-decorative-board"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'kaboodle-compatible-cabinet-door-16mm-decorative-board',
  'cabinet-doors',
  'Kaboodle Compatible',
  'Kaboodle Compatible Cabinet Door – 16mm Decorative Board',
  'Kaboodle Compatible Cabinet Door – 16mm Decorative Board',
  'Kaboodle Compatible Cabinet Door – 16mm Decorative Board',
  'Replacement cabinet doors in 16mm decorative board, cut to fit Kaboodle kitchen frames. Full Polytec, Laminex and Formica colour range. Pre-drilled to Kaboodle hinge positions.',
  'Replacement cabinet doors in 16mm decorative board, cut to fit Kaboodle kitchen frames. Full Polytec, Laminex and Formica colour range. Pre-drilled to Kaboodle hinge positions.',
  'Kaboodle kitchens from Bunnings are a solid starting point — the frames and hardware are well-made and the installation process is straightforward. Where they fall short is colour and finish choice, and that''s where these replacement doors come in. Cut from 16mm decorative board to fit standard Kaboodle cabinet openings, these doors are available in the full Polytec, Laminex and Formica colour and finish range — far beyond what Kaboodle stocks in store. Hinge holes are drilled to Kaboodle hinge positions, so the swap is as simple as removing the existing door and fitting the new one. Whether you''re building a new Kaboodle kitchen and want a better finish from the start, or refreshing an existing one, this is the most practical way to get the colour you actually want.',
  'Replacement Kaboodle cabinet doors in 16mm decorative board, made to measure in Perth WA. Full Polytec, Laminex and Formica range. Pre-drilled hinge holes. Request a quote.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  190,
  'door',
  'Cabinet Door',
  '16mm',
  '16mm Decorative Board',
  'kaboodle',
  'Kaboodle',
  null,
  'Flat slab / profile to order',
  'Cut to Kaboodle frame dimensions',
  'More colour choices for your Kaboodle kitchen',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified Kaboodle frame dimensions',
  'Yes – drilled to standard Kaboodle hinge positions',
  '["Fits Kaboodle kitchen frames","Full Polytec, Laminex and Formica colour range","Pre-drilled to Kaboodle hinge positions","Hinges available on request","Made to your exact frame dimensions","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["kaboodle-compatible-cabinet-door-18mm-decorative-board","kaboodle-compatible-cabinet-door-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'kaboodle-compatible-cabinet-door-18mm-decorative-board',
  'cabinet-doors',
  'Kaboodle Compatible',
  'Kaboodle Compatible Cabinet Door – 18mm Decorative Board',
  'Kaboodle Compatible Cabinet Door – 18mm Decorative Board',
  'Kaboodle Compatible Cabinet Door – 18mm Decorative Board',
  'Replacement cabinet doors in 18mm decorative board, cut to fit Kaboodle kitchen frames. Full Polytec, Laminex and Formica colour range. Pre-drilled to Kaboodle hinge positions.',
  'Replacement cabinet doors in 18mm decorative board, cut to fit Kaboodle kitchen frames. Full Polytec, Laminex and Formica colour range. Pre-drilled to Kaboodle hinge positions.',
  'If you''re after a door with a bit more substance than the standard Kaboodle offering, 18mm decorative board is worth considering. These doors are cut to fit standard Kaboodle cabinet openings and are available in the full Polytec, Laminex and Formica colour range. The extra 2mm makes a meaningful difference on larger door panels — pantry doors, overhead cabinet fronts and any door that takes frequent handling will feel noticeably more solid. Hinge holes are drilled to Kaboodle hinge positions, and we can supply the hinges if needed. Order alongside matching drawer fronts and panels for a consistent finish across the whole kitchen.',
  'Replacement Kaboodle cabinet doors in 18mm decorative board, made to measure in Perth WA. Full Polytec, Laminex and Formica range. Pre-drilled hinge holes.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  200,
  'door',
  'Cabinet Door',
  '18mm',
  '18mm Decorative Board',
  'kaboodle',
  'Kaboodle',
  null,
  'Flat slab / profile to order',
  'Cut to Kaboodle frame dimensions',
  'A heavier, more substantial door for your Kaboodle kitchen',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified Kaboodle frame dimensions',
  'Yes – drilled to standard Kaboodle hinge positions',
  '["Fits Kaboodle kitchen frames","Full Polytec, Laminex and Formica colour range","Pre-drilled to Kaboodle hinge positions","Hinges available on request","18mm thickness for pantry and overhead doors","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["kaboodle-compatible-cabinet-door-16mm-decorative-board","kaboodle-compatible-cabinet-door-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'kaboodle-compatible-drawer-front-16mm-decorative-board',
  'drawer-fronts',
  'Kaboodle Compatible',
  'Kaboodle Compatible Drawer Front – 16mm Decorative Board',
  'Kaboodle Compatible Drawer Front – 16mm Decorative Board',
  'Kaboodle Compatible Drawer Front – 16mm Decorative Board',
  'Replacement drawer fronts in 16mm decorative board, cut to fit Kaboodle drawer openings. Full Polytec, Laminex and Formica colour range.',
  'Replacement drawer fronts in 16mm decorative board, cut to fit Kaboodle drawer openings. Full Polytec, Laminex and Formica colour range.',
  'Bunnings stocks Kaboodle drawer fronts in a handful of colours — enough to get started, but not enough to get the kitchen you actually had in mind. These replacement fronts are cut from 16mm decorative board to fit standard Kaboodle drawer openings, and they''re available in the full Polytec, Laminex and Formica range so you can choose the colour and finish that suits your space rather than whatever''s available off the shelf. The fit is exact, the finish is clean, and if you''re ordering alongside cabinet doors and end panels we''ll make sure everything comes from the same colour run. It''s one of the most effective ways to make a Kaboodle kitchen feel completely your own.',
  'Replacement Kaboodle drawer fronts in 16mm decorative board, made to measure in Perth WA. Full Polytec, Laminex and Formica colour range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  210,
  'drawer-front',
  'Drawer Front',
  '16mm',
  '16mm Decorative Board',
  'kaboodle',
  'Kaboodle',
  null,
  'Flat slab / profile to order',
  'Cut to Kaboodle drawer dimensions',
  'Replacement drawer fronts that open up your Kaboodle colour options',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified Kaboodle drawer dimensions',
  null,
  '["Fits Kaboodle drawer openings","Full Polytec, Laminex and Formica colour range","Batch-matched with cabinet doors and panels on request","16mm thickness suits Kaboodle drawer hardware","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["kaboodle-compatible-drawer-front-18mm-decorative-board","kaboodle-compatible-drawer-front-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'kaboodle-compatible-drawer-front-18mm-decorative-board',
  'drawer-fronts',
  'Kaboodle Compatible',
  'Kaboodle Compatible Drawer Front – 18mm Decorative Board',
  'Kaboodle Compatible Drawer Front – 18mm Decorative Board',
  'Kaboodle Compatible Drawer Front – 18mm Decorative Board',
  'Replacement drawer fronts in 18mm decorative board, cut to fit Kaboodle drawer openings. Full Polytec, Laminex and Formica colour range. Matches 18mm Kaboodle cabinet doors.',
  'Replacement drawer fronts in 18mm decorative board, cut to fit Kaboodle drawer openings. Full Polytec, Laminex and Formica colour range. Matches 18mm Kaboodle cabinet doors.',
  'For those going the full upgrade on a Kaboodle kitchen, 18mm drawer fronts bring a noticeably more substantial feel compared to what comes in the box. Cut to fit standard Kaboodle drawer openings and available across the full Polytec, Laminex and Formica range, these fronts are made to your exact dimensions in our Perth workshop. The extra thickness is most noticeable on wider drawers — a full-width pot drawer or a wide base cabinet front will feel considerably more solid, and the edge profile is more pronounced. Order with matching 18mm cabinet doors and end panels to keep the finish consistent across the whole kitchen.',
  'Replacement Kaboodle drawer fronts in 18mm decorative board, made to measure in Perth WA. Full Polytec, Laminex and Formica range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  220,
  'drawer-front',
  'Drawer Front',
  '18mm',
  '18mm Decorative Board',
  'kaboodle',
  'Kaboodle',
  null,
  'Flat slab / profile to order',
  'Cut to Kaboodle drawer dimensions',
  'Heavier Kaboodle drawer fronts with a more premium feel',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified Kaboodle drawer dimensions',
  null,
  '["Fits Kaboodle drawer openings","Full Polytec, Laminex and Formica colour range","18mm thickness for a more substantial feel","Batch-matched with 18mm doors and panels on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["kaboodle-compatible-drawer-front-16mm-decorative-board","kaboodle-compatible-drawer-front-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'kaboodle-compatible-panel-16mm-decorative-board',
  'panels',
  'Kaboodle Compatible',
  'Kaboodle Compatible Panel – 16mm Decorative Board',
  'Kaboodle Compatible Panel – 16mm Decorative Board',
  'Kaboodle Compatible Panel – 16mm Decorative Board',
  'End panels in 16mm decorative board, cut to work with Kaboodle kitchen cabinets. Full Polytec, Laminex and Formica colour range. Order with matching doors and drawer fronts.',
  'End panels in 16mm decorative board, cut to work with Kaboodle kitchen cabinets. Full Polytec, Laminex and Formica colour range. Order with matching doors and drawer fronts.',
  'Kaboodle kitchens are designed to be installed against walls and other units, but where a side is exposed — the end of a kitchen run, an island cabinet, or a freestanding unit — you need a panel that looks like part of the design, not an afterthought. These end panels are cut from 16mm decorative board to work with standard Kaboodle cabinet dimensions, and are available across the full Polytec, Laminex and Formica colour range. The finish and edge quality matches the rest of our Kaboodle-compatible range, so when you order doors, drawer fronts and panels together you get a consistent result across the whole installation. If you''re not sure of the exact dimensions you need, get in touch and we can help you work it out.',
  'Replacement Kaboodle end panels in 16mm decorative board, made to measure in Perth WA. Full Polytec, Laminex and Formica range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  230,
  'panel',
  'Panel',
  '16mm',
  '16mm Decorative Board',
  'kaboodle',
  'Kaboodle',
  null,
  'Flat panel',
  'Cut to Kaboodle cabinet dimensions',
  'Finish the exposed sides of your Kaboodle kitchen properly',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified dimensions',
  null,
  '["Works with Kaboodle kitchen cabinets","Full Polytec, Laminex and Formica colour range","Batch-matched with doors and drawer fronts on request","Suitable for exposed island ends and run terminations","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the finished width and height you need in millimetres, then send through the application and visible edge details."},{"title":"Panel use","body":"Panels are supplied cut to size and are commonly used for end panels, returns, surrounds and visible cabinet sides."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["kaboodle-compatible-panel-18mm-decorative-board","kaboodle-compatible-panel-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'kaboodle-compatible-panel-18mm-decorative-board',
  'panels',
  'Kaboodle Compatible',
  'Kaboodle Compatible Panel – 18mm Decorative Board',
  'Kaboodle Compatible Panel – 18mm Decorative Board',
  'Kaboodle Compatible Panel – 18mm Decorative Board',
  'End panels in 18mm decorative board, cut to work with Kaboodle kitchen cabinets. Full Polytec, Laminex and Formica colour range. Matches 18mm Kaboodle doors and drawer fronts.',
  'End panels in 18mm decorative board, cut to work with Kaboodle kitchen cabinets. Full Polytec, Laminex and Formica colour range. Matches 18mm Kaboodle doors and drawer fronts.',
  'Where you want the end panels of your Kaboodle kitchen to feel as solid as the rest of the cabinetry, 18mm decorative board is the right call. Cut to work with standard Kaboodle cabinet dimensions and available across the full Polytec, Laminex and Formica colour range, these panels are made to your exact measurements in our Perth workshop. The added thickness works well on taller and wider panel applications — a full-height pantry end or a wide base cabinet side where the panel is a visible and tactile part of the kitchen. Order with your 18mm Kaboodle doors and drawer fronts and we''ll batch-match the finish so everything sits together consistently.',
  'Replacement Kaboodle end panels in 18mm decorative board, made to measure in Perth WA. Full Polytec, Laminex and Formica range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  240,
  'panel',
  'Panel',
  '18mm',
  '18mm Decorative Board',
  'kaboodle',
  'Kaboodle',
  null,
  'Flat panel',
  'Cut to Kaboodle cabinet dimensions',
  'Substantial end panels that complete your Kaboodle kitchen',
  'Polytec / Laminex / Formica',
  'Enquire for current lead times',
  'Yes – cut to your specified dimensions',
  null,
  '["Works with Kaboodle kitchen cabinets","Full Polytec, Laminex and Formica colour range","18mm thickness for full-height and wide panel applications","Batch-matched with 18mm doors and drawer fronts on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the finished width and height you need in millimetres, then send through the application and visible edge details."},{"title":"Panel use","body":"Panels are supplied cut to size and are commonly used for end panels, returns, surrounds and visible cabinet sides."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["kaboodle-compatible-panel-16mm-decorative-board","kaboodle-compatible-panel-thermolaminate"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'kaboodle-compatible-cabinet-door-thermolaminate',
  'cabinet-doors',
  'Kaboodle Compatible',
  'Kaboodle Compatible Cabinet Door – Thermolaminate',
  'Kaboodle Compatible Cabinet Door – Thermolaminate',
  'Kaboodle Compatible Cabinet Door – Thermolaminate',
  'Thermolaminate replacement doors for Kaboodle kitchens. Wrapped finish on all edges, full Polytec colour range, pre-drilled to Kaboodle hinge positions.',
  'Thermolaminate replacement doors for Kaboodle kitchens. Wrapped finish on all edges, full Polytec colour range, pre-drilled to Kaboodle hinge positions.',
  'Thermolaminate replacement doors for Kaboodle kitchens take the convenience of the Bunnings flat-pack system and give it a finish that genuinely looks custom. The thermolaminate wrap covers all four edges of each door, so there''s no raw edge line visible from any angle — front, side or when the door is open. Available across the full Polytec colour and texture range, including timber looks, stone-inspired finishes, mattes and high gloss, these doors give you far more choice than what Bunnings carries on the shelf. Hinge holes are drilled to Kaboodle hinge positions, and hinges are available if you need them. If you want the practicality of Kaboodle with a finish that makes the kitchen feel like it was made for the space, this is the product.',
  'Thermolaminate replacement doors for Kaboodle kitchens, made to measure in Perth WA. Wrapped finish, full Polytec colour range, pre-drilled hinge holes. Request a quote.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  250,
  'door',
  'Cabinet Door',
  'thermolaminate',
  'Thermolaminate',
  'kaboodle',
  'Kaboodle',
  null,
  'Flat slab / profile to order',
  'Cut to Kaboodle frame dimensions',
  'A seamlessly wrapped door upgrade for your Kaboodle kitchen',
  'Polytec',
  'Enquire for current lead times',
  'Yes – cut to your specified Kaboodle frame dimensions',
  'Yes – drilled to standard Kaboodle hinge positions',
  '["Fits Kaboodle kitchen frames","Wrapped finish with no visible raw edge","Full Polytec colour and texture range","Pre-drilled to Kaboodle hinge positions","Hinges available on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["kaboodle-compatible-cabinet-door-16mm-decorative-board","kaboodle-compatible-cabinet-door-18mm-decorative-board"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'kaboodle-compatible-drawer-front-thermolaminate',
  'drawer-fronts',
  'Kaboodle Compatible',
  'Kaboodle Compatible Drawer Front – Thermolaminate',
  'Kaboodle Compatible Drawer Front – Thermolaminate',
  'Kaboodle Compatible Drawer Front – Thermolaminate',
  'Thermolaminate replacement drawer fronts for Kaboodle kitchens. Wrapped finish on all edges, full Polytec colour range. Order with matching thermolaminate doors for a consistent result.',
  'Thermolaminate replacement drawer fronts for Kaboodle kitchens. Wrapped finish on all edges, full Polytec colour range. Order with matching thermolaminate doors for a consistent result.',
  'Swapping out Kaboodle drawer fronts for thermolaminate versions is one of the quickest ways to lift the whole feel of the kitchen. The wrapped finish means the decorative film covers all four edges — so when a drawer is open or the front is seen from the side, the finish is clean and consistent rather than showing a raw board edge. Available in the full Polytec colour and texture range to fit standard Kaboodle drawer openings, every front is cut to your exact dimensions in Perth. Order alongside your Kaboodle thermolaminate doors and panels for a result that looks cohesive from every angle.',
  'Thermolaminate replacement Kaboodle drawer fronts, made to measure in Perth WA. Wrapped finish, full Polytec colour range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  260,
  'drawer-front',
  'Drawer Front',
  'thermolaminate',
  'Thermolaminate',
  'kaboodle',
  'Kaboodle',
  null,
  'Flat slab / profile to order',
  'Cut to Kaboodle drawer dimensions',
  'Thermolaminate drawer fronts that transform your Kaboodle kitchen',
  'Polytec',
  'Enquire for current lead times',
  'Yes – cut to your specified Kaboodle drawer dimensions',
  null,
  '["Fits Kaboodle drawer openings","Wrapped finish with no visible raw edge","Full Polytec colour and texture range","Batch-matched with thermolaminate doors and panels on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing front, then send through your dimensions and cabinet type."},{"title":"Drilling and hardware","body":"Door drilling and hinge supply can be included where required. Let us know your cabinet system and hardware requirements when requesting a quote."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["kaboodle-compatible-drawer-front-16mm-decorative-board","kaboodle-compatible-drawer-front-18mm-decorative-board"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'kaboodle-compatible-panel-thermolaminate',
  'panels',
  'Kaboodle Compatible',
  'Kaboodle Compatible Panel – Thermolaminate',
  'Kaboodle Compatible Panel – Thermolaminate',
  'Kaboodle Compatible Panel – Thermolaminate',
  'Thermolaminate end panels for Kaboodle kitchens. Wrapped finish on all edges, full Polytec colour range. Matched to your thermolaminate doors and drawer fronts.',
  'Thermolaminate end panels for Kaboodle kitchens. Wrapped finish on all edges, full Polytec colour range. Matched to your thermolaminate doors and drawer fronts.',
  'When a side of your Kaboodle cabinet run is visible — an island end, a run termination, a unit sitting away from the wall — a thermolaminate panel finishes it properly. The wrapped film covers all four edges so the panel looks complete from every angle, not just from the front. Available across the full Polytec colour and texture range and cut to dimensions that work with standard Kaboodle cabinets, every panel is made to your measurements in our Perth workshop. Order alongside your Kaboodle thermolaminate doors and drawer fronts and we''ll match the batch so the colour and texture are consistent right across the installation.',
  'Thermolaminate Kaboodle end panels made to measure in Perth WA. Wrapped finish, full Polytec colour range.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  null,
  true,
  270,
  'panel',
  'Panel',
  'thermolaminate',
  'Thermolaminate',
  'kaboodle',
  'Kaboodle',
  null,
  'Flat panel',
  'Cut to Kaboodle cabinet dimensions',
  'Wrap the exposed sides of your Kaboodle installation in a seamless finish',
  'Polytec',
  'Enquire for current lead times',
  'Yes – cut to your specified dimensions',
  null,
  '["Works with Kaboodle kitchen cabinets","Wrapped finish with no visible raw edge","Full Polytec colour and texture range","Batch-matched with thermolaminate doors and drawer fronts on request","Cut and finished in Perth"]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"title":"How to measure","body":"Measure the finished width and height you need in millimetres, then send through the application and visible edge details."},{"title":"Panel use","body":"Panels are supplied cut to size and are commonly used for end panels, returns, surrounds and visible cabinet sides."},{"title":"Delivery and lead times","body":"Products are made to order in Perth. Lead times vary depending on current workshop volume and material availability."}]'::jsonb,
  '["kaboodle-compatible-panel-16mm-decorative-board","kaboodle-compatible-panel-18mm-decorative-board"]'::jsonb,
  '{}'::jsonb
)
on conflict (slug) do update set
  category = excluded.category,
  eyebrow = excluded.eyebrow,
  name = excluded.name,
  card_title = excluded.card_title,
  page_title = excluded.page_title,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  detail_description = excluded.detail_description,
  meta_description = excluded.meta_description,
  cta_label = excluded.cta_label,
  cta_url = excluded.cta_url,
  currency = excluded.currency,
  price_from = excluded.price_from,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  type = excluded.type,
  type_label = excluded.type_label,
  material = excluded.material,
  material_label = excluded.material_label,
  compatibility = excluded.compatibility,
  compatibility_label = excluded.compatibility_label,
  ikea_system = excluded.ikea_system,
  style = excluded.style,
  standard_size = excluded.standard_size,
  hero_caption = excluded.hero_caption,
  finish_brand = excluded.finish_brand,
  lead_time = excluded.lead_time,
  made_to_measure = excluded.made_to_measure,
  pre_drilled = excluded.pre_drilled,
  features = excluded.features,
  finishes = excluded.finishes,
  gallery_images = excluded.gallery_images,
  pricing_rows = excluded.pricing_rows,
  info_cards = excluded.info_cards,
  related_product_ids = excluded.related_product_ids,
  product_options = excluded.product_options;

insert into public.product_quote_configs (
  product_id,
  is_enabled,
  quote_title,
  quote_description,
  finish_set_id,
  colour_set_id,
  profile_type_set_id,
  profile_set_id,
  edge_set_id,
  hinge_set_id,
  groups_json,
  dimensions_json,
  pricing_json
)
select
  p.id,
  seed.is_enabled,
  'Online Quotation Request',
  'Create a detailed quote request for this product.',
  null,
  null,
  null,
  null,
  null,
  null,
  '{}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb
from (
  values
  ('cabinet-door-16mm-decorative-board', true),
  ('cabinet-door-18mm-decorative-board', true),
  ('drawer-front-16mm-decorative-board', true),
  ('drawer-front-18mm-decorative-board', true),
  ('panel-16mm-decorative-board', true),
  ('panel-18mm-decorative-board', true),
  ('cabinet-door-thermolaminate', true),
  ('drawer-front-thermolaminate', true),
  ('panel-thermolaminate', true),
  ('ikea-compatible-cabinet-door-16mm-decorative-board', true),
  ('ikea-compatible-cabinet-door-18mm-decorative-board', true),
  ('ikea-compatible-drawer-front-16mm-decorative-board', true),
  ('ikea-compatible-drawer-front-18mm-decorative-board', true),
  ('ikea-compatible-panel-16mm-decorative-board', true),
  ('ikea-compatible-panel-18mm-decorative-board', true),
  ('ikea-compatible-cabinet-door-thermolaminate', true),
  ('ikea-compatible-drawer-front-thermolaminate', true),
  ('ikea-compatible-panel-thermolaminate', true),
  ('kaboodle-compatible-cabinet-door-16mm-decorative-board', true),
  ('kaboodle-compatible-cabinet-door-18mm-decorative-board', true),
  ('kaboodle-compatible-drawer-front-16mm-decorative-board', true),
  ('kaboodle-compatible-drawer-front-18mm-decorative-board', true),
  ('kaboodle-compatible-panel-16mm-decorative-board', true),
  ('kaboodle-compatible-panel-18mm-decorative-board', true),
  ('kaboodle-compatible-cabinet-door-thermolaminate', true),
  ('kaboodle-compatible-drawer-front-thermolaminate', true),
  ('kaboodle-compatible-panel-thermolaminate', true)
) as seed(slug, is_enabled)
join public.products p on p.slug = seed.slug
on conflict (product_id) do update set
  is_enabled = excluded.is_enabled,
  quote_title = excluded.quote_title,
  quote_description = excluded.quote_description;

notify pgrst, 'reload schema';
