create extension if not exists "pgcrypto";

-- This replaces the current product library rows with the original example products.
-- It intentionally clears product media mappings and quote configs first because those
-- records point at the products being replaced.
do $$
begin
  if to_regclass('public.product_images') is not null then
    delete from public.product_images;
  end if;

  if to_regclass('public.product_quote_configs') is not null then
    delete from public.product_quote_configs;
  end if;
end;
$$;

delete from public.products;

insert into public.products (
  id,
  slug,
  category,
  eyebrow,
  name,
  card_title,
  page_title,
  short_description,
  long_description,
  detail_description,
  meta_description,
  cta_label,
  cta_url,
  currency,
  price_from,
  is_active,
  sort_order,
  type,
  type_label,
  material,
  material_label,
  compatibility,
  compatibility_label,
  ikea_system,
  style,
  standard_size,
  hero_caption,
  finish_brand,
  lead_time,
  made_to_measure,
  pre_drilled,
  features,
  finishes,
  gallery_images,
  pricing_rows,
  info_cards,
  related_product_ids,
  product_options
)
values
(
  gen_random_uuid(),
  'shaker-profile-door',
  'cabinet-doors',
  'Cabinet Doors',
  'Shaker profile door',
  'Shaker profile door',
  'Shaker profile door',
  'Classic thermolaminate shaker profile, available across the full Polytec colour range. Pre-drilled for standard Metod hinges. A popular choice for kitchen upgrades.',
  'Classic thermolaminate shaker profile, available across the full Polytec colour range. Pre-drilled for standard Metod hinges. A popular choice for kitchen upgrades.',
  'A classic thermolaminate shaker profile door, made to your exact measurements and finished in your choice of Polytec colour. Pre-drilled for standard IKEA Metod hinges so it is ready to hang straight out of the box. A popular choice for kitchen upgrades and rental refreshes across Perth.',
  'Shaker profile thermolaminate cabinet door made to measure in Perth.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  85.00,
  true,
  1,
  'door',
  'Door',
  'thermolaminate',
  'Thermolaminate',
  'ikea',
  'IKEA Metod',
  'metod',
  'Shaker profile',
  '600 x 700mm',
  'Shown in Polytec Matte White',
  'Polytec',
  'Enquire for current times',
  'Yes, custom sizes available',
  'Yes, hinge holes included',
  '["Available across the Polytec thermolaminate colour range","Made to your exact measurements","Pre-drilled for standard IKEA Metod hinges","Suitable for kitchen, laundry and bathroom upgrades"]'::jsonb,
  '[{"name":"Gloss","description":"A sleek, mirror-like surface that brings brightness and polish to any space."},{"name":"Ravine","description":"A textured linear woodgrain finish that adds natural character."},{"name":"Smooth","description":"A refined low-sheen surface with a soft, uniform texture."},{"name":"Texture","description":"A practical lightly embossed finish for everyday use."},{"name":"Woodmatt","description":"A matt finish with a realistic woodgrain effect."}]'::jsonb,
  '[]'::jsonb,
  '[{"size":"600 x 700mm","description":"Standard size","price":85},{"size":"Custom narrow","description":"Smaller width or height","price":67},{"size":"Custom tall","description":"Taller panel or door","price":107,"popular":true},{"size":"Custom wide","description":"Wider face or panel","price":119},{"size":"Oversized","description":"Large format custom piece","price":143}]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing face. Send through your dimensions and cabinet type, and we will confirm the correct sizing before production."},{"title":"Pre-drilling and hinges","body":"Doors and drawer fronts can be drilled to suit common cabinet systems. Let us know your cabinet brand and hardware requirements when you request a quote."},{"title":"Delivery and lead times","body":"We ship flat-rate across Perth metro. Lead times vary depending on current order volume, so enquire at the time of ordering for current availability."}]'::jsonb,
  '["shaker-drawer-front","profiled-edge-door","flat-slab-drawer-front"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'flat-slab-drawer-front',
  'drawer-fronts',
  'Drawer Fronts',
  'Flat slab drawer front',
  'Flat slab drawer front',
  'Flat slab drawer front',
  'Clean, flat face in 16mm decorative board. Suits contemporary and minimalist interiors. Compatible with Besta drawer runners. Available in all Polytec finishes.',
  'Clean, flat face in 16mm decorative board. Suits contemporary and minimalist interiors. Compatible with Besta drawer runners. Available in all Polytec finishes.',
  'A clean flat slab drawer front made from 16mm decorative board and cut to your measurements. It suits contemporary kitchens, bathroom vanities and furniture-style IKEA Besta upgrades where a sharp, simple face is the right fit.',
  'Flat slab 16mm decorative board drawer front made to measure in Perth.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  55.00,
  true,
  2,
  'drawer-front',
  'Drawer front',
  '16mm',
  '16mm board',
  'ikea',
  'IKEA Besta',
  'besta',
  'Flat slab',
  '600 x 200mm',
  'Shown in Polytec Linen',
  'Polytec',
  'Enquire for current times',
  'Yes, custom sizes available',
  'Yes, drawer fixing holes available',
  '["Clean flat slab face","Cut to your exact measurements","Suitable for IKEA Besta drawer upgrades","Available in Polytec decorative board finishes"]'::jsonb,
  '[{"name":"Gloss","description":"A bright polished decorative board finish."},{"name":"Legato","description":"A refined low-sheen decorative board finish."},{"name":"Ravine","description":"A textured linear woodgrain finish."},{"name":"Venette","description":"A soft matt decorative board finish."},{"name":"Woodmatt","description":"A durable matt woodgrain decorative board finish."}]'::jsonb,
  '[]'::jsonb,
  '[{"size":"600 x 200mm","description":"Standard size","price":55},{"size":"Custom narrow","description":"Smaller width or height","price":45},{"size":"Custom tall","description":"Taller panel or door","price":77,"popular":true},{"size":"Custom wide","description":"Wider face or panel","price":89},{"size":"Oversized","description":"Large format custom piece","price":113}]'::jsonb,
  '[{"title":"How to measure","body":"Measure the existing drawer front or cabinet opening and send through the width and height in millimetres."},{"title":"Drawer fixing","body":"Drawer fronts can be supplied for common cabinet systems. Confirm your drawer hardware when requesting a quote."},{"title":"Delivery and lead times","body":"We ship flat-rate across Perth metro. Lead times vary depending on current order volume."}]'::jsonb,
  '["besta-side-panel","shaker-drawer-front","shaker-profile-door"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'end-panel',
  'panels',
  'Panels',
  'End panel',
  'End panel',
  'End panel',
  '18mm decorative board end panel for a seamless, finished look on exposed cabinet sides. Cut to your exact dimensions and available in all Polytec finishes.',
  '18mm decorative board end panel for a seamless, finished look on exposed cabinet sides. Cut to your exact dimensions and available in all Polytec finishes.',
  'An 18mm decorative board end panel for finishing exposed cabinet sides with a seamless matching surface. Each panel is cut to your exact dimensions and can be supplied for Kaboodle cabinetry, custom carcasses and matching built-in details.',
  '18mm decorative board end panel cut to size in Perth.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  110.00,
  true,
  3,
  'panel',
  'Panel',
  '18mm',
  '18mm board',
  'kaboodle',
  'Kaboodle',
  null,
  'Flat panel',
  '600 x 900mm',
  'Shown in Polytec Stone Grey',
  'Polytec',
  'Enquire for current times',
  'Yes, custom sizes available',
  'Not applicable',
  '["Finishes exposed cabinet sides","Cut to your exact dimensions","Suitable for Kaboodle and custom cabinetry","Available in Polytec decorative board finishes"]'::jsonb,
  '[{"name":"Gloss","description":"A bright polished decorative board finish."},{"name":"Legato","description":"A refined low-sheen decorative board finish."},{"name":"Ravine","description":"A textured linear woodgrain finish."},{"name":"Venette","description":"A soft matt decorative board finish."},{"name":"Woodmatt","description":"A durable matt woodgrain decorative board finish."}]'::jsonb,
  '[]'::jsonb,
  '[{"size":"600 x 900mm","description":"Standard size","price":110},{"size":"Custom narrow","description":"Smaller width or height","price":92},{"size":"Custom tall","description":"Taller panel or door","price":132,"popular":true},{"size":"Custom wide","description":"Wider face or panel","price":144},{"size":"Oversized","description":"Large format custom piece","price":168}]'::jsonb,
  '[{"title":"How to measure","body":"Measure the exposed side or panel area and send through your finished width and height in millimetres."},{"title":"Panel use","body":"Panels are supplied cut to size and do not require hinge or drawer drilling."},{"title":"Delivery and lead times","body":"We ship flat-rate across Perth metro. Lead times vary depending on current order volume."}]'::jsonb,
  '["profiled-edge-door","besta-side-panel","flat-slab-drawer-front"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'compact-laminate-wardrobe-door',
  'cabinet-doors',
  'Wardrobe Doors',
  'Compact laminate wardrobe door',
  'Compact laminate wardrobe door',
  'Compact laminate wardrobe door',
  'Highly durable compact laminate wardrobe door, moisture and impact resistant. Pre-drilled for Pax hinges. An excellent choice for high-traffic areas.',
  'Highly durable compact laminate wardrobe door, moisture and impact resistant. Pre-drilled for Pax hinges. An excellent choice for high-traffic areas.',
  'A durable compact laminate wardrobe door made for IKEA Pax upgrades and high-use spaces. The surface is moisture and impact resistant, with hinge drilling available so the new doors are ready to fit to your existing wardrobe system.',
  'Compact laminate wardrobe door for IKEA Pax upgrades.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  135.00,
  true,
  4,
  'door',
  'Door',
  'compact',
  'Compact laminate',
  'ikea',
  'IKEA Pax',
  'pax',
  'Wardrobe door',
  '500 x 2000mm',
  'Shown in Polytec Forest',
  'Polytec',
  'Enquire for current times',
  'Yes, custom sizes available',
  'Yes, hinge holes included',
  '["Moisture and impact resistant","Made for IKEA Pax upgrades","Cut to your exact measurements","Suitable for high-traffic spaces"]'::jsonb,
  '[{"name":"Matt","description":"A practical compact laminate matt surface."},{"name":"Smooth","description":"A smooth compact laminate finish for stone and solid colour looks."},{"name":"Woodmatt","description":"A timber-look compact laminate finish."}]'::jsonb,
  '[]'::jsonb,
  '[{"size":"500 x 2000mm","description":"Standard size","price":135},{"size":"Custom narrow","description":"Smaller width or height","price":117},{"size":"Custom tall","description":"Taller panel or door","price":157,"popular":true},{"size":"Custom wide","description":"Wider face or panel","price":169},{"size":"Oversized","description":"Large format custom piece","price":193}]'::jsonb,
  '[{"title":"How to measure","body":"Measure your existing wardrobe door or required opening and confirm hinge positions where applicable."},{"title":"Pre-drilling and hinges","body":"Hinge drilling is available for common wardrobe systems including IKEA Pax."},{"title":"Delivery and lead times","body":"We ship flat-rate across Perth metro. Lead times vary depending on current order volume."}]'::jsonb,
  '["compact-laminate-table-top","besta-side-panel","shaker-profile-door"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'profiled-edge-door',
  'cabinet-doors',
  'Cabinet Doors',
  'Profiled edge door',
  'Profiled edge door',
  'Profiled edge door',
  'Thermolaminate door with a routed front profile for added character and depth. A great way to lift a standard Kaboodle carcass with a truly custom finish.',
  'Thermolaminate door with a routed front profile for added character and depth. A great way to lift a standard Kaboodle carcass with a truly custom finish.',
  'A thermolaminate door with a routed front profile for added depth and a more bespoke cabinet finish. It is a practical way to upgrade standard Kaboodle carcasses while keeping your existing layout and cabinet boxes.',
  'Profiled edge thermolaminate cabinet door made to measure in Perth.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  90.00,
  true,
  5,
  'door',
  'Door',
  'thermolaminate',
  'Thermolaminate',
  'kaboodle',
  'Kaboodle',
  null,
  'Profiled edge',
  '600 x 700mm',
  'Shown in Polytec Pebble',
  'Polytec',
  'Enquire for current times',
  'Yes, custom sizes available',
  'Yes, hinge holes included',
  '["Routed front profile","Made in thermolaminate","Suitable for Kaboodle carcass upgrades","Available across the Polytec thermolaminate colour range"]'::jsonb,
  '[{"name":"Gloss","description":"A sleek, mirror-like surface that brings brightness and polish to any space."},{"name":"Ravine","description":"A textured linear woodgrain finish that adds natural character."},{"name":"Smooth","description":"A refined low-sheen surface with a soft, uniform texture."},{"name":"Texture","description":"A practical lightly embossed finish for everyday use."},{"name":"Woodmatt","description":"A matt finish with a realistic woodgrain effect."}]'::jsonb,
  '[]'::jsonb,
  '[{"size":"600 x 700mm","description":"Standard size","price":90},{"size":"Custom narrow","description":"Smaller width or height","price":72},{"size":"Custom tall","description":"Taller panel or door","price":112,"popular":true},{"size":"Custom wide","description":"Wider face or panel","price":124},{"size":"Oversized","description":"Large format custom piece","price":148}]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your cabinet opening or existing face and confirm your cabinet system."},{"title":"Pre-drilling and hinges","body":"Doors can be drilled to suit common cabinet systems. Let us know your hinge requirements when you request a quote."},{"title":"Delivery and lead times","body":"We ship flat-rate across Perth metro. Lead times vary depending on current order volume."}]'::jsonb,
  '["shaker-profile-door","end-panel","shaker-drawer-front"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'shaker-drawer-front',
  'drawer-fronts',
  'Drawer Fronts',
  'Shaker drawer front',
  'Shaker drawer front',
  'Shaker drawer front',
  'Matching thermolaminate shaker drawer front to complement our shaker door range. Pre-drilled for Metod runners. Order alongside your doors for a fully coordinated look.',
  'Matching thermolaminate shaker drawer front to complement our shaker door range. Pre-drilled for Metod runners. Order alongside your doors for a fully coordinated look.',
  'A matching thermolaminate shaker drawer front designed to pair with our shaker cabinet doors. Each front is made to measure, finished in your chosen Polytec colour and drilled to suit your cabinet range where required.',
  'Thermolaminate shaker drawer front made to measure in Perth.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  65.00,
  true,
  6,
  'drawer-front',
  'Drawer front',
  'thermolaminate',
  'Thermolaminate',
  'ikea',
  'IKEA Metod',
  'metod',
  'Shaker profile',
  '600 x 200mm',
  'Shown in Polytec Matte White',
  'Polytec',
  'Enquire for current times',
  'Yes, custom sizes available',
  'Yes, drawer fixing holes available',
  '["Matches shaker cabinet doors","Made to your exact measurements","Available across the Polytec thermolaminate colour range","Suitable for coordinated kitchen upgrades"]'::jsonb,
  '[{"name":"Gloss","description":"A sleek, mirror-like surface that brings brightness and polish to any space."},{"name":"Ravine","description":"A textured linear woodgrain finish that adds natural character."},{"name":"Smooth","description":"A refined low-sheen surface with a soft, uniform texture."},{"name":"Texture","description":"A practical lightly embossed finish for everyday use."},{"name":"Woodmatt","description":"A matt finish with a realistic woodgrain effect."}]'::jsonb,
  '[]'::jsonb,
  '[{"size":"600 x 200mm","description":"Standard size","price":65},{"size":"Custom narrow","description":"Smaller width or height","price":47},{"size":"Custom tall","description":"Taller panel or door","price":87,"popular":true},{"size":"Custom wide","description":"Wider face or panel","price":99},{"size":"Oversized","description":"Large format custom piece","price":123}]'::jsonb,
  '[{"title":"How to measure","body":"Measure the width and height of your existing drawer front or required cabinet face."},{"title":"Drawer fixing","body":"Drawer fronts can be supplied for common cabinet systems. Confirm your drawer hardware when requesting a quote."},{"title":"Delivery and lead times","body":"We ship flat-rate across Perth metro. Lead times vary depending on current order volume."}]'::jsonb,
  '["shaker-profile-door","flat-slab-drawer-front","profiled-edge-door"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'besta-side-panel',
  'panels',
  'Panels',
  'Besta side panel',
  'Besta side panel',
  'Besta side panel',
  '18mm decorative side panel cut to Besta dimensions for a built-in, furniture-quality finish. Covers the raw sides of your Besta units with a matching Polytec surface.',
  '18mm decorative side panel cut to Besta dimensions for a built-in, furniture-quality finish. Covers the raw sides of your Besta units with a matching Polytec surface.',
  'An 18mm decorative side panel cut to suit IKEA Besta dimensions, giving freestanding units a built-in furniture-quality finish. Use it to cover exposed sides and create a matching Polytec look across your cabinet run.',
  '18mm decorative board side panel for IKEA Besta upgrades.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  95.00,
  true,
  7,
  'panel',
  'Panel',
  '18mm',
  '18mm board',
  'ikea',
  'IKEA Besta',
  'besta',
  'Side panel',
  '400 x 740mm',
  'Shown in Polytec Warm Oak',
  'Polytec',
  'Enquire for current times',
  'Yes, custom sizes available',
  'Not applicable',
  '["Cut to suit IKEA Besta dimensions","Creates a built-in furniture finish","Covers exposed cabinet sides","Available in Polytec decorative board finishes"]'::jsonb,
  '[{"name":"Gloss","description":"A bright polished decorative board finish."},{"name":"Legato","description":"A refined low-sheen decorative board finish."},{"name":"Ravine","description":"A textured linear woodgrain finish."},{"name":"Venette","description":"A soft matt decorative board finish."},{"name":"Woodmatt","description":"A durable matt woodgrain decorative board finish."}]'::jsonb,
  '[]'::jsonb,
  '[{"size":"400 x 740mm","description":"Standard size","price":95},{"size":"Custom narrow","description":"Smaller width or height","price":77},{"size":"Custom tall","description":"Taller panel or door","price":117,"popular":true},{"size":"Custom wide","description":"Wider face or panel","price":129},{"size":"Oversized","description":"Large format custom piece","price":153}]'::jsonb,
  '[{"title":"How to measure","body":"Measure the exposed side of your Besta unit or the panel size required for your layout."},{"title":"Panel use","body":"Panels are supplied cut to size and do not require hinge or drawer drilling."},{"title":"Delivery and lead times","body":"We ship flat-rate across Perth metro. Lead times vary depending on current order volume."}]'::jsonb,
  '["flat-slab-drawer-front","end-panel","compact-laminate-wardrobe-door"]'::jsonb,
  '{}'::jsonb
),
(
  gen_random_uuid(),
  'compact-laminate-table-top',
  'panels',
  'Table Tops',
  'Compact laminate table top',
  'Compact laminate table top',
  'Compact laminate table top',
  'Heavy-duty compact laminate table top, cut to your specified dimensions. Scratch, moisture and heat resistant. Suitable for kitchen islands, laundry benches and home offices.',
  'Heavy-duty compact laminate table top, cut to your specified dimensions. Scratch, moisture and heat resistant. Suitable for kitchen islands, laundry benches and home offices.',
  'A heavy-duty compact laminate table top cut to your nominated dimensions. The surface is scratch, moisture and heat resistant, making it suitable for kitchen islands, laundry benches, study nooks and work surfaces.',
  'Compact laminate table top cut to size in Perth.',
  'Open online quotation request form',
  '/request-quote',
  'AUD',
  180.00,
  true,
  8,
  'table-top',
  'Table top',
  'compact',
  'Compact laminate',
  'all',
  null,
  null,
  'Table top',
  '900 x 600mm',
  'Shown in Polytec Matte Black',
  'Polytec',
  'Enquire for current times',
  'Yes, custom sizes available',
  'Not applicable',
  '["Heavy-duty compact laminate surface","Scratch, moisture and heat resistant","Cut to your nominated dimensions","Suitable for islands, laundry benches and home offices"]'::jsonb,
  '[{"name":"Matt","description":"A practical compact laminate matt surface."},{"name":"Smooth","description":"A smooth compact laminate finish for stone and solid colour looks."},{"name":"Woodmatt","description":"A timber-look compact laminate finish."}]'::jsonb,
  '[]'::jsonb,
  '[{"size":"900 x 600mm","description":"Standard size","price":180},{"size":"Custom narrow","description":"Smaller width or height","price":162},{"size":"Custom tall","description":"Taller panel or door","price":202,"popular":true},{"size":"Custom wide","description":"Wider face or panel","price":214},{"size":"Oversized","description":"Large format custom piece","price":238}]'::jsonb,
  '[{"title":"How to measure","body":"Measure the final table top, bench or work surface size you need in millimetres."},{"title":"Panel use","body":"Table tops are supplied cut to size and do not require hinge or drawer drilling."},{"title":"Delivery and lead times","body":"We ship flat-rate across Perth metro. Lead times vary depending on current order volume."}]'::jsonb,
  '["compact-laminate-wardrobe-door","end-panel","besta-side-panel"]'::jsonb,
  '{}'::jsonb
);
