import { FlatCompat } from "@eslint/eslintrc";
import pcdRules from "./eslint-rules/no-read-before-declared.mjs";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

// The point of this config is `no-undef`.
//
// The design tool's geometry lives in .js files, which get no type checking at
// all — and `next build` compiles straight past an identifier that doesn't
// exist, because a ReferenceError is a runtime problem, not a compile one.
// That is not hypothetical: moving endPanelThicknessMm into a shared lib left
// DesignCanvas still calling it, and the build was perfectly green. It would
// have thrown the moment any end-panelled cabinet rendered. The identical
// rename in CabinetConfigurator.tsx was caught instantly by TypeScript — the
// .js half of the codebase simply had no equivalent net.
//
// Severity is chosen deliberately, because `next build` fails on ESLint
// ERRORS. This config was added to a codebase that predates it, and Next's
// defaults flag ~20 pre-existing style issues in the public site (<a> vs
// <Link>). Shipping those as errors would have turned a green build red over
// things nobody is fixing today, and the pressure would then be to disable
// linting entirely — losing no-undef with it.
//
// So: rules that catch genuine breakage are errors. Style and perf advice is a
// warning — visible, not blocking. Tighten these once the backlog is cleared.
export default [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      // EVERY build output folder, not just .next.
      //
      // This was ".next/**" alone, and a build into its own folder leaves
      // .next-verify or .next-build sitting beside it, which lint then walked:
      // 5,381 of the 5,419 errors this config reported on 21 September 2026
      // came from minified code nobody here wrote, and they buried the 38 that
      // were ours. See PCD_DIST_DIR in next.config.mjs for why those folders
      // exist at all.
      ".next*/**",
      "node_modules/**",
      "supabase/**",
      // Generated by Next on every build; not ours to lint.
      "next-env.d.ts",
    ],
  },
  {
    // ---- The September 2026 rule ----
    //
    // A let or const read before the line that creates it. Every quote in the
    // admin was a dead page for a day because of one, and the build, the 3265
    // tests and no-undef all passed it through. An error, not a warning,
    // because the page it lands on does not render at all.
    //
    // Scoped to every file we write, .js and .tsx alike: this is a runtime
    // fault, so unlike no-undef below, TypeScript does not catch it either.
    // The reasoning, and why the stock no-use-before-define cannot be used
    // instead, is in eslint-rules/no-read-before-declared.mjs.
    files: ["**/*.js", "**/*.jsx", "**/*.mjs", "**/*.ts", "**/*.tsx"],
    plugins: { pcd: pcdRules },
    rules: { "pcd/no-read-before-declared": "error" },
  },
  {
    rules: {
      // ---- Warnings: pre-existing debt, surfaced but not blocking ----
      // The other half of a half-finished refactor — a definition left behind
      // after its callers moved away. Warn rather than error: there are a
      // handful already, and none of them are hurting anything.
      "no-unused-vars": ["warn", { args: "none", ignoreRestSiblings: true }],
      "@typescript-eslint/no-unused-vars": ["warn", { args: "none", ignoreRestSiblings: true }],
      "@next/next/no-html-link-for-pages": "warn",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/triple-slash-reference": "off",
      "react-hooks/exhaustive-deps": "warn",
      "react/no-unescaped-entities": "warn",
      "@next/next/no-img-element": "off",
    },
  },
  {
    // no-undef is scoped to the untyped half of the codebase, and deliberately
    // NOT applied to .ts/.tsx.
    //
    // TypeScript already reports undefined identifiers, and it does it better:
    // ESLint can't tell a runtime reference from a type-only one, so it flags
    // `React.FormEvent` in a .tsx file as an undefined variable even though no
    // React value is referenced at all. Running it there produces noise, not
    // safety. The .js files are the ones with no net.
    files: ["**/*.js", "**/*.jsx", "**/*.mjs"],
    rules: {
      // The whole reason this config exists.
      "no-undef": "error",
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        navigator: "readonly",
        process: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Response: "readonly",
        Request: "readonly",
        Headers: "readonly",
        Blob: "readonly",
        File: "readonly",
        FormData: "readonly",
        AbortController: "readonly",
        SVGSVGElement: "readonly",
        Image: "readonly",
        crypto: "readonly",
        structuredClone: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        alert: "readonly",
        confirm: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        module: "writable",
        require: "readonly",
      },
    },
  },
];
